# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Retrode3
#

# bus
obj-$(CONFIG_RETRODE3_BUS)		+= retrode3-core.o retrode3-bus.o

# clients
obj-$(CONFIG_RETRODE3_MEGADRIVE)	+= retrode3-core.o retrode3-megadrive.o
obj-$(CONFIG_RETRODE3_NES)		+= retrode3-core.o retrode3-nes.o
obj-$(CONFIG_RETRODE3_SNES)		+= retrode3-core.o retrode3-snes.o
obj-$(CONFIG_RETRODE3_CONTROLLER)	+= retrode3-core.o retrode3-controller.o
