ccflags-y += -I$(srctree)/drivers/media/platform/ingenic-vcodec/felix/libh264/
ccflags-y += -I$(srctree)/drivers/media/platform/ingenic-vcodec/felix/libh264/include/


libh264-y +=	\
	log.o	\
	mem.o	\
	h264_picture.o		\
	golomb.o		\
	h264data.o		\
	h264_refs.o		\
	mathtables.o		\
	h2645_parse.o		\
	h264_parse.o		\
	h264_direct.o		\
	h264_ps.o		\
	h264_sei.o		\
	buffer.o		\
	vpu_ops.o		\
	h264_slice.o		\
	h264dec.o

obj-y += libh264.o


