#ifndef __LINUX_OMAP3_CONTROL_H
#define __LINUX_OMAP3_CONTROL_H

#define CONTROL_PADCONF_OFF	0x00
#define CONTROL_DEVCONF0	0x04
#define CONTROL_MSUSPENDMUX_0	0x20
#define CONTROL_MSUSPENDMUX_1	0x24
#define CONTROL_MSUSPENDMUX_2	0x28
#define CONTROL_MSUSPENDMUX_3	0x2C
#define CONTROL_MSUSPENDMUX_4	0x30
#define CONTROL_MSUSPENDMUX_5	0x34
#define CONTROL_PROT_CTRL	0x40
#define CONTROL_DEVCONF1	0x68
#define CONTROL_PROT_ERR_STATUS	0x74
#define CONTROL_PROT_ERR_STATUS_DEBUG	0x78
#define CONTROL_STATUS			0x80

#define DEVCONF1_TVOUTBYPASS	BIT(18)
#define DEVCONF1_TVACEN		BIT(11)

#endif /* __LINUX_OMAP3_CONTROL_H */
