#!/bin/bash

if [ -z "$1" ] ; then
	echo "Usage: $0 <DEVICE>    eg, $0 GTA02"
	exit 1
fi

NAME=`echo $1 | cut -d'-' -f1`

../../dfu-util/src/dfu-util -a 3 -d 0x1d50:0x5119 -D $1/uImage-$NAME.bin
if [ $? -eq 1 ] ; then
../../dfu-util/src/dfu-util -a 3 -d 0x1d50:0x5120 -D $1/uImage-$NAME.bin
../../dfu-util/src/dfu-util -a 3 -d 0x1d50:0x5119 -D $1/uImage-$NAME.bin
fi


