ingenic_helix-y :=	helix_drv.o \
			jpge.o \
			jpgd.o \
			default_sliceinfo.o \
			helix_ops.o \
			api/helix_x264_enc.o \
			api/helix_jpeg_enc.o \
			api/helix_jpeg_dec.o \
			h264enc/set.o  \
			h264enc/cabac.o \
			h264enc/common.o \
			h264enc/slice.o \
			h264e_rc.o \
			h264e_rc_nl.o

obj-$(CONFIG_INGENIC_HELIX) += ingenic_helix.o

