obj-y += axp-mfd.o

#Make this built-in, so that it will be loaded before I2C driver

#obj-$(CONFIG_KP_AXP) += axp-board.o
obj-$(CONFIG_KP_AXP) += axp-regu.o
obj-$(CONFIG_KP_AXP) += axp-sply.o
#obj-$(CONFIG_KP_AXP) += axp-gpio.o
obj-$(CONFIG_KP_AXP) += virtual216_dev.o
obj-$(CONFIG_KP_AXP) += virtual216.o


