#
# Makefile for digital gyroscope sensor drivers
#

adis16060-y             := adis16060_core.o
obj-$(CONFIG_ADIS16060) += adis16060.o
itg3200-y		:= itg3200_core.o
obj-$(CONFIG_ITG3200)	+= itg3200.o
