#ifndef TIZIANO_MAP__H
#define TIZIANO_MAP__H
#ifndef TIZIANO_BASE
#define TIZIANO_BASE  0x0
#endif
#ifndef TIZIANO_MAN
#define TIZIANO_MAN 3
#endif

//============================================================
// BASE ADDRESS
//============================================================
#define    VIC_BASE              (TIZIANO_BASE + 0x10000)
#define    TOP_BASE              (TIZIANO_BASE + 0x00000)
#define    IP_BASE               (TIZIANO_BASE + 0x00100)
#define    DPC_BASE              (TIZIANO_BASE + 0x00200)
#define    GIB_BASE              (TIZIANO_BASE + 0x00400)
#define    LSC_BASE              (TIZIANO_BASE + 0x00500)
#define    AG_BASE               (TIZIANO_BASE + 0x00600)
#define    AE_BASE               (TIZIANO_BASE + 0x00700)
#define    AWB_BASE              (TIZIANO_BASE + 0x00800)
#define    AF_BASE               (TIZIANO_BASE + 0x00900)
#define    ADR_BASE              (TIZIANO_BASE + 0x00A00)
#define    IRINT_BASE            (TIZIANO_BASE + 0x00F00)
#define    DMSC_BASE             (TIZIANO_BASE + 0x01000)
#define    CCM_BASE              (TIZIANO_BASE + 0x01200)
#define    DEFOG_BASE            (TIZIANO_BASE + 0x01300)
#define    CSC_BASE              (TIZIANO_BASE + 0x01700)
#define    CLM_BASE              (TIZIANO_BASE + 0x01800)
#define    SP_BASE               (TIZIANO_BASE + 0x01900)
#define    MDNS_BASE             (TIZIANO_BASE + 0x01B00)
#define    SDNS_BASE             (TIZIANO_BASE + 0x02000)
#define    HLDC_BASE             (TIZIANO_BASE + 0x02200)
#define    MSCA_BASE             (TIZIANO_BASE + 0x02300)

#define    DPC_MEM_BASE          (TIZIANO_BASE + 0x04000)
#define    LSC_MEM_BASE          (TIZIANO_BASE + 0x06000)
#define    GIB_MEM_BASE          (TIZIANO_BASE + 0x08000)
#define    AE_HIST_MEM_BASE      (TIZIANO_BASE + 0x08200)
#define    R_GAMMA_MEM_BASE      (TIZIANO_BASE + 0x08A00)
#define    G_GAMMA_MEM_BASE      (TIZIANO_BASE + 0x08C00)
#define    B_GAMMA_MEM_BASE      (TIZIANO_BASE + 0x08E00)
#define    DEFOG_MEM_BASE        (TIZIANO_BASE + 0x09000)
#define    CLM_H_0_MEM_BASE      (TIZIANO_BASE + 0x0A000)
#define    CLM_H_1_MEM_BASE      (TIZIANO_BASE + 0x0A800)
#define    CLM_S_0_MEM_BASE      (TIZIANO_BASE + 0x0B000)
#define    CLM_S_1_MEM_BASE      (TIZIANO_BASE + 0x0B800)

#if 0
//============================================================
// VIC
//============================================================
#define    VIC_ADDR_CONTROL                       (VIC_BASE + 0x00)
#define    VIC_ADDR_RESOLUTION                    (VIC_BASE + 0x04)
#define    VIC_ADDR_FRAME_ECC                     (VIC_BASE + 0x08)
#define    VIC_ADDR_INTF_TYPE                     (VIC_BASE + 0x0C)
#define    VIC_ADDR_BT_CFG                        (VIC_BASE + 0x10)
#define    VIC_ADDR_PCLK_GATE                     (VIC_BASE + 0x1C)
#define    VIC_ADDR_HOR_PARA0                     (VIC_BASE + 0x20)
#define    VIC_ADDR_HOR_PARA1                     (VIC_BASE + 0x24)
#define    VIC_ADDR_VER_PARA0                     (VIC_BASE + 0x30)
#define    VIC_ADDR_VER_PARA1                     (VIC_BASE + 0x34)
#define    VIC_ADDR_VER_PARA2                     (VIC_BASE + 0x38)
#define    VIC_ADDR_VER_PARA3                     (VIC_BASE + 0x3C)
#define    VIC_ADDR_GLB_CFG                       (VIC_BASE + 0x50)
#define    VIC_ADDR_AB_VLA                        (VIC_BASE + 0x54)
#define    VIC_ADDR_HBLK_R                        (VIC_BASE + 0x58)
#define    VIC_ADDR_VBLK_R                        (VIC_BASE + 0x5C)
#define    VIC_ADDR_SAV_VALUE0                    (VIC_BASE + 0x60)
#define    VIC_ADDR_EAV_VALUE0                    (VIC_BASE + 0x64)
#define    VIC_ADDR_SAV_VALUE1                    (VIC_BASE + 0x68)
#define    VIC_ADDR_EAV_VALUE1                    (VIC_BASE + 0x6C)
#define    VIC_ADDR_SAV_VALUE2                    (VIC_BASE + 0x70)
#define    VIC_ADDR_EAV_VALUE2                    (VIC_BASE + 0x74)
#define    VIC_ADDR_WORK_STATE                    (VIC_BASE + 0x0090)
#define    VIC_ADDR_PIX_REG                       (VIC_BASE + 0x0094)
#define    VIC_ADDR_LINE_REG                      (VIC_BASE + 0x0098)
#define    VIC_ADDR_OFIFO_CNT                     (VIC_BASE + 0x009C)
#define    VIC_ADDR_BF_BAR_CTRL                   (VIC_BASE + 0x00A0)
#define    VIC_ADDR_BF_BAR_BLANK                  (VIC_BASE + 0x00A4)
#define    VIC_ADDR_AF_BAR_CTRL                   (VIC_BASE + 0x00B0)
#define    VIC_ADDR_AF_BAR_BLANK                  (VIC_BASE + 0x00B4)
#define    VIC_ADDR_WHITE_BAR                     (VIC_BASE + 0x00C0)
#define    VIC_ADDR_BLACK_BAR                     (VIC_BASE + 0x00C4)
#define    VIC_ADDR_BLUE_BAR                      (VIC_BASE + 0x00C8)
#define    VIC_ADDR_GREEN_BAR                     (VIC_BASE + 0x00CC)
#define    VIC_ADDR_RED_BAR                       (VIC_BASE + 0x00D0)
#define    VIC_ADDR_CYAN_BAR                      (VIC_BASE + 0x00D4)
#define    VIC_ADDR_YELLOW_BAR                    (VIC_BASE + 0x00D8)
#define    VIC_ADDR_MAGENTA_BAR                   (VIC_BASE + 0x00DC)
#define    VIC_ADDR_WHITE_BAR2                    (VIC_BASE + 0x00E0)
#define    VIC_ADDR_BLACK_BAR2                    (VIC_BASE + 0x00E4)
#define    VIC_ADDR_BLUE_BAR2                     (VIC_BASE + 0x00E8)
#define    VIC_ADDR_GREEN_BAR2                    (VIC_BASE + 0x00EC)
#define    VIC_ADDR_RED_BAR2                      (VIC_BASE + 0x00F0)
#define    VIC_ADDR_CYAN_BAR2                     (VIC_BASE + 0x00F4)
#define    VIC_ADDR_YELLOW_BAR2                   (VIC_BASE + 0x00F8)
#define    VIC_ADDR_MAGENTA_BAR2                  (VIC_BASE + 0x00FC)
#define    VIC_ADDR_INT_STA                       (VIC_BASE + 0x0100)
#define    VIC_ADDR_INT_MASK                      (VIC_BASE + 0x0104)
#define    VIC_ADDR_INT_CLR                       (VIC_BASE + 0x0108)
#define    VIC_ADDR_DMA_CONFIGURE                 (VIC_BASE + 0x0200)
#define    VIC_ADDR_DMA_RES_R                     (VIC_BASE + 0x0204)
#define    VIC_ADDR_DMA_RESET                     (VIC_BASE + 0x0208)
#define    VIC_ADDR_DMA_Y_CH_BANK_CONTROL         (VIC_BASE + 0x0210)
#define    VIC_ADDR_DMA_Y_CH_LINE_STRIDE          (VIC_BASE + 0x0214)
#define    VIC_ADDR_DMA_Y_CH_BANK0_ADDR           (VIC_BASE + 0x0218)
#define    VIC_ADDR_DMA_Y_CH_BANK1_ADDR           (VIC_BASE + 0x021c)
#define    VIC_ADDR_DMA_Y_CH_BANK2_ADDR           (VIC_BASE + 0x0220)
#define    VIC_ADDR_DMA_Y_CH_BANK3_ADDR           (VIC_BASE + 0x0224)
#define    VIC_ADDR_DMA_Y_CH_BANK4_ADDR           (VIC_BASE + 0x0228)
#define    VIC_ADDR_DMA_UV_CH_BANK_CONTROL        (VIC_BASE + 0x0230)
#define    VIC_ADDR_DMA_UV_CH_LINE_STRIDE         (VIC_BASE + 0x0234)
#define    VIC_ADDR_DMA_UV_CH_BANK0_ADDR          (VIC_BASE + 0x0238)
#define    VIC_ADDR_DMA_UV_CH_BANK1_ADDR          (VIC_BASE + 0x023c)
#define    VIC_ADDR_DMA_UV_CH_BANK2_ADDR          (VIC_BASE + 0x0240)
#define    VIC_ADDR_DMA_UV_CH_BANK3_ADDR          (VIC_BASE + 0x0244)
#define    VIC_ADDR_DMA_UV_CH_BANK4_ADDR          (VIC_BASE + 0x0248)
#define    VIC_ADDR_SYFIFO_USED                   (VIC_BASE + 0x0300)
#define    VIC_ADDR_FR_DONE_CNT                   (VIC_BASE + 0x0304)
#define    VIC_ADDR_DVP_SIZE                      (VIC_BASE + 0x0308)
#define    VIC_ADDR_DVP_WORK_STA                  (VIC_BASE + 0x030C)

#endif

//============================================================
// TOP
//============================================================
#define    DPC			(0 << 0)
#define    GIB			(0 << 1)
#define    LSC			(0 << 2)
#define    AWB			(0 << 3)
#define    ADR			(1 << 4)
#define    DMS			(0 << 5)
#define    CCM			(0 << 6)
#define    GAMMA		(0 << 7)
#define	   DEFOG		(1 << 8)
#define    CLM			(0 << 9)
#define    Y_SHARPEN		(0 << 10)
#define    MDNS			(0 << 11)
#define    SDNS			(0 << 12)
#define    HLDC			(1 << 13)
#define    TP			(1 << 14)
#define    FONT			(1 << 15)
#define    SEL			(0 << 31)
#define    TIZIANO_BYPASS_INIT (DPC|GIB|LSC|AWB|ADR|DMS|CCM|GAMMA|DEFOG|CLM|Y_SHARPEN|MDNS|SDNS|HLDC|TP|FONT|SEL)

#define    TIZIANO_FM_SIZE				(TOP_BASE + 0X0004)
#define    TIZIANO_BATER_TYPE				(TOP_BASE + 0X0008)
#define    TIZAINO_BYPASS_CON				(TOP_BASE + 0X000C)
#define    TIZIANO_TOP_CON				(TOP_BASE + 0X0010)
#define    TIZIANO_REG_CON				(TOP_BASE + 0X001C)
#define    TIZAINO_INT_EN				(TOP_BASE + 0X0080)

#define    TOP_CTRL_ADDR_VERSION                        (TOP_BASE + 0x0000)
#define    TOP_CTRL_ADDR_FM_SIZE                        (TOP_BASE + 0x0004)
#define    TOP_CTRL_ADDR_BAYER_TYPE                     (TOP_BASE + 0x0008)
#define    TOP_CTRL_ADDR_BYPASS_CON                     (TOP_BASE + 0x000C)
#define    TOP_CTRL_ADDR_TOP_CON                        (TOP_BASE + 0x0010)
#define    TOP_CTRL_ADDR_TOP_STATE                      (TOP_BASE + 0x0014)
#define    TOP_CTRL_ADDR_LINE_SPACE                     (TOP_BASE + 0x0018)
#define    TOP_CTRL_ADDR_REG_CON                        (TOP_BASE + 0x001C)
#define    TOP_CTRL_ADDR_DMA_RC_TRIG                    (TOP_BASE + 0x0030)
#define    TOP_CTRL_ADDR_DMA_RC_CON                     (TOP_BASE + 0x0034)
#define    TOP_CTRL_ADDR_DMA_RC_ADDR                    (TOP_BASE + 0x0038)
#define    TOP_CTRL_ADDR_DMA_RC_STATE                   (TOP_BASE + 0x003C)
#define    TOP_CTRL_ADDR_DMA_RC_APB_WR_DATA             (TOP_BASE + 0x0040)
#define    TOP_CTRL_ADDR_DMA_RC_APB_WR_ADDR             (TOP_BASE + 0x0044)
#define    TOP_CTRL_ADDR_DMA_RD_CON                     (TOP_BASE + 0x0050)
#define    TOP_CTRL_ADDR_DMA_WR_CON                     (TOP_BASE + 0x0054)
#define    TOP_CTRL_ADDR_DMA_FR_WR_CON                  (TOP_BASE + 0x0058)
#define    TOP_CTRL_ADDR_DMA_STA_WR_CON                 (TOP_BASE + 0x005C)
#define    TOP_CTRL_ADDR_DMA_RD_DEBUG                   (TOP_BASE + 0x0060)
#define    TOP_CTRL_ADDR_DMA_WR_DEBUG                   (TOP_BASE + 0x0064)
#define    TOP_CTRL_ADDR_DMA_FR_WR_DEBUG                (TOP_BASE + 0x0068)
#define    TOP_CTRL_ADDR_DMA_STA_WR_DEBUG               (TOP_BASE + 0x006C)
#define    TOP_CTRL_ADDR_INT_EN                         (TOP_BASE + 0x0080)
#define    TOP_CTRL_ADDR_INT_REG                        (TOP_BASE + 0x0084)
#define    TOP_CTRL_ADDR_INT_CLR                        (TOP_BASE + 0x0088)
#define    TOP_CTRL_ADDR_TP_FREERUN                     (TOP_BASE + 0x00A0)
#define    TOP_CTRL_ADDR_TP_CON                         (TOP_BASE + 0x00A4)
#define    TOP_CTRL_ADDR_TP_SIZE                        (TOP_BASE + 0x00A8)
#define    TOP_CTRL_ADDR_TP_FONT                        (TOP_BASE + 0x00AC)
#define    TOP_CTRL_ADDR_TP_FLICK                       (TOP_BASE + 0x00B0)
#define    TOP_CTRL_ADDR_TP_CS_TYPE                     (TOP_BASE + 0x00B4)
#define    TOP_CTRL_ADDR_TP_CS_FCLO                     (TOP_BASE + 0x00B8)
#define    TOP_CTRL_ADDR_TP_CS_BCLO                     (TOP_BASE + 0x00BC)

//============================================================
// Input Interface
//============================================================
#define    INPUT_CTRL_ADDR_IP_TRIG                      (IP_BASE + 0x0000)
#define    INPUT_CTRL_ADDR_CONTROL                      (IP_BASE + 0x0004)
#define    INPUT_CTRL_ADDR_CHK_TRIG                     (IP_BASE + 0x0008)
#define    INPUT_CTRL_ADDR_CHK_TIME                     (IP_BASE + 0x000C)
#define    INPUT_CTRL_ADDR_CHK_CNT                      (IP_BASE + 0x0010)
#define    INPUT_CTRL_ADDR_CHK_FR_CNT                   (IP_BASE + 0x0014)
#define    INPUT_CTRL_ADDR_IP_STATE                     (IP_BASE + 0x0018)
#define    INPUT_CTRL_ADDR_IN_CNT                       (IP_BASE + 0x001C)
#define    INPUT_CTRL_ADDR_OUT_CNT                      (IP_BASE + 0x0020)

//============================================================
// DPC
//============================================================
#if 0
#define    DPC_ADDR_SYNC                          (DPC_BASE + 0x0000)
#define    DPC_ADDR_S_EN                          (DPC_BASE + 0x0004)
#define    DPC_ADDR_S_OC_BLEND_ALPHA              (DPC_BASE + 0x0008)
#define    DPC_ADDR_OC_BLEND_ALPHA                (DPC_BASE + 0x000C)
#define    DPC_ADDR_SD_LV1_SLOPE                  (DPC_BASE + 0x0010)
#define    DPC_ADDR_SD_LV2_SLOPE                  (DPC_BASE + 0x0014)
#define    DPC_ADDR_LS_BLEND_ALPHA_RB             (DPC_BASE + 0x0018)
#define    DPC_ADDR_LV1_DIFF_THRES_RB             (DPC_BASE + 0x001C)
#define    DPC_ADDR_SD_LV2_DIFF_THRES_RB          (DPC_BASE + 0x0020)
#define    DPC_ADDR_SD_LV2_P0_THRES_RB            (DPC_BASE + 0x0024)
#define    DPC_ADDR_SD_LV2_P2_THRES_RB            (DPC_BASE + 0x0028)
#define    DPC_ADDR_SD_LV2_P0_DIST_THRES_RB       (DPC_BASE + 0x002C)
#define    DPC_ADDR_SD_LV2_P2_DIST_THRES_RB       (DPC_BASE + 0x0030)
#define    DPC_ADDR_LD_LV2_THRES_RB               (DPC_BASE + 0x0034)
#define    DPC_ADDR_LS_BLEND_ALPHA_G              (DPC_BASE + 0x0038)
#define    DPC_ADDR_LV1_DIFF_THRES_G              (DPC_BASE + 0x003C)
#define    DPC_ADDR_SD_LV2_DIFF_THRES_G           (DPC_BASE + 0x0040)
#define    DPC_ADDR_SD_LV2_P0_THRES_G             (DPC_BASE + 0x0044)
#define    DPC_ADDR_SD_LV2_P2_THRES_G             (DPC_BASE + 0x0048)
#define    DPC_ADDR_SD_LV2_P0_DIST_THRES_G        (DPC_BASE + 0x004C)
#define    DPC_ADDR_SD_LV2_P2_DIST_THRES_G        (DPC_BASE + 0x0050)
#define    DPC_ADDR_LD_LV2_THRES_G                (DPC_BASE + 0x0054)
#define    DPC_ADDR_CTR_FUNC_EN                   (DPC_BASE + 0x0058)
#define    DPC_ADDR_CTR_MD_SEG_OPT                (DPC_BASE + 0x005C)
#define    DPC_ADDR_CTR_BASE_THRES                (DPC_BASE + 0x0060)
#define    DPC_ADDR_RDNS_FUNC_EN                  (DPC_BASE + 0x0064)
#define    DPC_ADDR_RDNS_FLAT_THRES               (DPC_BASE + 0x0068)
#define    DPC_ADDR_RDNS_TEXT_THRES               (DPC_BASE + 0x006C)
#define    DPC_ADDR_RDNS_SIGMA_X1                 (DPC_BASE + 0x0070)
#define    DPC_ADDR_RDNS_STD                      (DPC_BASE + 0x0074)
#define    DPC_ADDR_RDNS_RB_GAUS_SIGMA            (DPC_BASE + 0x0078)
#define    DPC_ADDR_RDNS_G_SIGMA_X                (DPC_BASE + 0x007C)
#define    DPC_ADDR_RDNS_G_SIGMA_S                (DPC_BASE + 0x0080)
#define    DPC_ADDR_RDNS_RB_SIGMA_X               (DPC_BASE + 0x0084)
#define    DPC_ADDR_RDNS_RB_SIGMA_S               (DPC_BASE + 0x0088)
#define    DPC_ADDR_CTR_MD_NP_ARRAY_RG0           (DPC_BASE + 0x008C)
#define    DPC_ADDR_CTR_MD_NP_ARRAY_RG1           (DPC_BASE + 0x0090)
#define    DPC_ADDR_CTR_MD_NP_ARRAY_RG2           (DPC_BASE + 0x0094)
#define    DPC_ADDR_CTR_MD_NP_ARRAY_RG3           (DPC_BASE + 0x0098)
#define    DPC_ADDR_RDNS_STD_NP_ARRAY_RG0         (DPC_BASE + 0x009C)
#define    DPC_ADDR_RDNS_STD_NP_ARRAY_RG1         (DPC_BASE + 0x00A0)
#define    DPC_ADDR_RDNS_STD_NP_ARRAY_RG2         (DPC_BASE + 0x00A4)
#define    DPC_ADDR_RDNS_STD_NP_ARRAY_RG3         (DPC_BASE + 0x00A8)
#define    DPC_ADDR_RDNS_STD_NP_ARRAY_RG4         (DPC_BASE + 0x00AC)
#define    DPC_ADDR_RDNS_STD_NP_ARRAY_RG5         (DPC_BASE + 0x00B0)
#define    DPC_ADDR_RDNS_STD_NP_ARRAY_RG6         (DPC_BASE + 0x00B4)
#define    DPC_ADDR_RDNS_STD_NP_ARRAY_RG7         (DPC_BASE + 0x00B8)
#define    DPC_ADDR_RDNS_G_LUM_NP_ARRAY_RG0       (DPC_BASE + 0x00BC)
#define    DPC_ADDR_RDNS_G_LUM_NP_ARRAY_RG1       (DPC_BASE + 0x00C0)
#define    DPC_ADDR_RDNS_G_LUM_NP_ARRAY_RG2       (DPC_BASE + 0x00C4)
#define    DPC_ADDR_RDNS_G_LUM_NP_ARRAY_RG3       (DPC_BASE + 0x00C8)
#define    DPC_ADDR_RDNS_G_LUM_NP_ARRAY_RG4       (DPC_BASE + 0x00CC)
#define    DPC_ADDR_RDNS_G_LUM_NP_ARRAY_RG5       (DPC_BASE + 0x00D0)
#define    DPC_ADDR_RDNS_G_LUM_NP_ARRAY_RG6       (DPC_BASE + 0x00D4)
#define    DPC_ADDR_RDNS_G_LUM_NP_ARRAY_RG7       (DPC_BASE + 0x00D8)
#define    DPC_ADDR_RDNS_G_STD_NP_ARRAY_RG0       (DPC_BASE + 0x00DC)
#define    DPC_ADDR_RDNS_G_STD_NP_ARRAY_RG1       (DPC_BASE + 0x00E0)
#define    DPC_ADDR_RDNS_G_STD_NP_ARRAY_RG2       (DPC_BASE + 0x00E4)
#define    DPC_ADDR_RDNS_G_STD_NP_ARRAY_RG3       (DPC_BASE + 0x00E8)
#define    DPC_ADDR_RDNS_G_STD_NP_ARRAY_RG4       (DPC_BASE + 0x00EC)
#define    DPC_ADDR_RDNS_G_STD_NP_ARRAY_RG5       (DPC_BASE + 0x00F0)
#define    DPC_ADDR_RDNS_G_STD_NP_ARRAY_RG6       (DPC_BASE + 0x00F4)
#define    DPC_ADDR_RDNS_G_STD_NP_ARRAY_RG7       (DPC_BASE + 0x00F8)
#define    DPC_ADDR_RDNS_RB_LUM_NP_ARRAY_RG0      (DPC_BASE + 0x00FC)
#define    DPC_ADDR_RDNS_RB_LUM_NP_ARRAY_RG1      (DPC_BASE + 0x0100)
#define    DPC_ADDR_RDNS_RB_LUM_NP_ARRAY_RG2      (DPC_BASE + 0x0104)
#define    DPC_ADDR_RDNS_RB_LUM_NP_ARRAY_RG3      (DPC_BASE + 0x0108)
#define    DPC_ADDR_RDNS_RB_LUM_NP_ARRAY_RG4      (DPC_BASE + 0x010C)
#define    DPC_ADDR_RDNS_RB_LUM_NP_ARRAY_RG5      (DPC_BASE + 0x0110)
#define    DPC_ADDR_RDNS_RB_LUM_NP_ARRAY_RG6      (DPC_BASE + 0x0114)
#define    DPC_ADDR_RDNS_RB_LUM_NP_ARRAY_RG7      (DPC_BASE + 0x0118)
#define    DPC_ADDR_RDNS_RB_STD_NP_ARRAY_RG0      (DPC_BASE + 0x011C)
#define    DPC_ADDR_RDNS_RB_STD_NP_ARRAY_RG1      (DPC_BASE + 0x0120)
#define    DPC_ADDR_RDNS_RB_STD_NP_ARRAY_RG2      (DPC_BASE + 0x0124)
#define    DPC_ADDR_RDNS_RB_STD_NP_ARRAY_RG3      (DPC_BASE + 0x0128)
#define    DPC_ADDR_RDNS_RB_STD_NP_ARRAY_RG4      (DPC_BASE + 0x012C)
#define    DPC_ADDR_RDNS_RB_STD_NP_ARRAY_RG5      (DPC_BASE + 0x0130)
#define    DPC_ADDR_RDNS_RB_STD_NP_ARRAY_RG6      (DPC_BASE + 0x0134)
#define    DPC_ADDR_RDNS_RB_STD_NP_ARRAY_RG7      (DPC_BASE + 0x0138)
#define    DPC_ADDR_SDP_NUM                       (DPC_BASE + 0x013C)
#define    DPC_ADDR_SP_DEBUG_REG_0                (DPC_BASE + 0x0140)
#define    DPC_ADDR_SP_DEBUG_REG_1                (DPC_BASE + 0x0144)

//============================================================
// GIB
//============================================================
#define    GIB_ADDR_REG_CTRL                      (GIB_BASE + 0x0000)
#define    GIB_ADDR_CONFIG                        (GIB_BASE + 0x0004)
#define    GIB_ADDR_R_G                           (GIB_BASE + 0x0008)
#define    GIB_ADDR_B_IR                          (GIB_BASE + 0x000c)
#define    GIB_ADDR_DEIRM_R12                     (GIB_BASE + 0x0010)
#define    GIB_ADDR_DEIRM_R34                     (GIB_BASE + 0x0014)
#define    GIB_ADDR_DEIRM_C1                      (GIB_BASE + 0x0018)
#define    GIB_ADDR_DEIRM_G12                     (GIB_BASE + 0x001c)
#define    GIB_ADDR_DEIRM_G34                     (GIB_BASE + 0x0020)
#define    GIB_ADDR_DEIRM_C2                      (GIB_BASE + 0x0024)
#define    GIB_ADDR_DEIRM_B12                     (GIB_BASE + 0x0028)
#define    GIB_ADDR_DEIRM_B34                     (GIB_BASE + 0x002c)
#define    GIB_ADDR_DEIRM_C3                      (GIB_BASE + 0x0030)
#define    GIB_ADDR_DEIRM_BLC12                   (GIB_BASE + 0x0034)
#define    GIB_ADDR_DEIRM_BLC34                   (GIB_BASE + 0x0038)
#define    GIB_ADDR_DEIRM_BLC5                    (GIB_BASE + 0x003c)
#define    GIB_ADDR_DEBUG0                        (GIB_BASE + 0x0040)
#define    GIB_DEIR_R_BASE                        (GIB_MEM_BASE + 0x0000)
#define    GIB_DEIR_G_BASE                        (GIB_MEM_BASE + 0x0080)
#define    GIB_DEIR_B_BASE                        (GIB_MEM_BASE + 0x0100)

//============================================================
// LSC
//============================================================
#define    LSC_ADDR_T_VERSION                     (LSC_BASE + 0x0000)
#define    LSC_ADDR_T_DBG_SEL                     (LSC_BASE + 0x0004)
#define    LSC_ADDR_T_DBG_VALUE                   (LSC_BASE + 0x0008)
#define    LSC_ADDR_MESH_SIZE                     (LSC_BASE + 0x0010)
#define    LSC_ADDR_MESH_SCALE                    (LSC_BASE + 0x0014)
#define    LSC_ADDR_LUT_STRIDE                    (LSC_BASE + 0x0018)

//============================================================
// AG
//============================================================
#define    AWB_GAIN_ADDR_REG_CTRL                 (AG_BASE + 0x0000)
#define    AWB_GAIN_ADDR_R_G                      (AG_BASE + 0x0004)
#define    AWB_GAIN_ADDR_B_IR                     (AG_BASE + 0x0008)
#define    AWB_GAIN_ADDR_DEBUG0                   (AG_BASE + 0x000c)

//============================================================
// AE
//============================================================
#define    AE_STAT_ADDR_REG_CTRL                  (AE_BASE + 0x0000)
#define    AE_STAT_ADDR_ZONE_NUM_START            (AE_BASE + 0x0004)
#define    AE_STAT_ADDR_HOR_ZONE_SIZE_14          (AE_BASE + 0x0008)
#define    AE_STAT_ADDR_HOR_ZONE_SIZE_58          (AE_BASE + 0x000c)
#define    AE_STAT_ADDR_HOR_ZONE_SIZE_912         (AE_BASE + 0x0010)
#define    AE_STAT_ADDR_HOR_ZONE_SIZE_1315        (AE_BASE + 0x0014)
#define    AE_STAT_ADDR_VER_ZONE_SIZE_14          (AE_BASE + 0x0018)
#define    AE_STAT_ADDR_VER_ZONE_SIZE_58          (AE_BASE + 0x001c)
#define    AE_STAT_ADDR_VER_ZONE_SIZE_912         (AE_BASE + 0x0020)
#define    AE_STAT_ADDR_VER_ZONE_SIZE_1315        (AE_BASE + 0x0024)
#define    AE_STAT_ADDR_LUM_TH_FREQ               (AE_BASE + 0x0028)
#define    AE_STAT_ADDR_AE_DMA_BASE_1             (AE_BASE + 0x002c)
#define    AE_STAT_ADDR_AE_DMA_BASE_2             (AE_BASE + 0x0030)
#define    AE_STAT_ADDR_AE_DMA_BASE_3             (AE_BASE + 0x0034)
#define    AE_STAT_ADDR_AE_DMA_BASE_4             (AE_BASE + 0x0038)
#define    AE_STAT_ADDR_HIST_DMA_BASE_1           (AE_BASE + 0x003c)
#define    AE_STAT_ADDR_HIST_DMA_BASE_2           (AE_BASE + 0x0040)
#define    AE_STAT_ADDR_HIST_DMA_BASE_3           (AE_BASE + 0x0044)
#define    AE_STAT_ADDR_HIST_DMA_BASE_4           (AE_BASE + 0x0048)
#define    AE_STAT_ADDR_DMA_BASE_NUM              (AE_BASE + 0x004c)
#define    AE_STAT_ADDR_DMA_INFO                  (AE_BASE + 0x0050)
#define    AE_STAT_ADDR_DEBUG0                    (AE_BASE + 0x0054)
#define    AE_STAT_ADDR_DEBUG1                    (AE_BASE + 0x0058)

//============================================================
// AWB
//============================================================
#define    AWB_STAT_ADDR_REG_CTRL                 (AWB_BASE + 0x0000)
#define    AWB_STAT_ADDR_ZONE_NUM_START           (AWB_BASE + 0x0004)
#define    AWB_STAT_ADDR_HOR_ZONE_SIZE_14         (AWB_BASE + 0x0008)
#define    AWB_STAT_ADDR_HOR_ZONE_SIZE_58         (AWB_BASE + 0x000c)
#define    AWB_STAT_ADDR_HOR_ZONE_SIZE_912        (AWB_BASE + 0x0010)
#define    AWB_STAT_ADDR_HOR_ZONE_SIZE_1315       (AWB_BASE + 0x0014)
#define    AWB_STAT_ADDR_VER_ZONE_SIZE_14         (AWB_BASE + 0x0018)
#define    AWB_STAT_ADDR_VER_ZONE_SIZE_58         (AWB_BASE + 0x001c)
#define    AWB_STAT_ADDR_VER_ZONE_SIZE_912        (AWB_BASE + 0x0020)
#define    AWB_STAT_ADDR_VER_ZONE_SIZE_1315       (AWB_BASE + 0x0024)
#define    AWB_STAT_ADDR_RG_TH                    (AWB_BASE + 0x0028)
#define    AWB_STAT_ADDR_BG_TH                    (AWB_BASE + 0x002c)
#define    AWB_STAT_ADDR_K1_A1                    (AWB_BASE + 0x0030)
#define    AWB_STAT_ADDR_K2_A2                    (AWB_BASE + 0x0034)
#define    AWB_STAT_ADDR_LUM_TH_FREQ              (AWB_BASE + 0x0038)
#define    AWB_STAT_ADDR_AWB_DMA_BASE_1           (AWB_BASE + 0x003c)
#define    AWB_STAT_ADDR_AWB_DMA_BASE_2           (AWB_BASE + 0x0040)
#define    AWB_STAT_ADDR_AWB_DMA_BASE_3           (AWB_BASE + 0x0044)
#define    AWB_STAT_ADDR_AWB_DMA_BASE_4           (AWB_BASE + 0x0048)
#define    AWB_STAT_ADDR_DMA_BASE_NUM             (AWB_BASE + 0x004c)
#define    AWB_STAT_ADDR_DMA_INFO                 (AWB_BASE + 0x0050)
#define    AWB_STAT_ADDR_DEBUG0                   (AWB_BASE + 0x0054)
#define    AWB_STAT_ADDR_DEBUG1                   (AWB_BASE + 0x0058)

//============================================================
// AF
//============================================================
#define    AF_STAT_ADDR_REG_CTRL                  (AF_BASE + 0x0000)
#define    AF_STAT_ADDR_ZONE_NUM_START            (AF_BASE + 0x0004)
#define    AF_STAT_ADDR_HOR_ZONE_SIZE_14          (AF_BASE + 0x0008)
#define    AF_STAT_ADDR_HOR_ZONE_SIZE_58          (AF_BASE + 0x000c)
#define    AF_STAT_ADDR_HOR_ZONE_SIZE_912         (AF_BASE + 0x0010)
#define    AF_STAT_ADDR_HOR_ZONE_SIZE_1315        (AF_BASE + 0x0014)
#define    AF_STAT_ADDR_VER_ZONE_SIZE_14          (AF_BASE + 0x0018)
#define    AF_STAT_ADDR_VER_ZONE_SIZE_58          (AF_BASE + 0x001c)
#define    AF_STAT_ADDR_VER_ZONE_SIZE_912         (AF_BASE + 0x0020)
#define    AF_STAT_ADDR_VER_ZONE_SIZE_1315        (AF_BASE + 0x0024)
#define    AF_STAT_ADDR_FREQ_IIR_EN_LUM_TH        (AF_BASE + 0x0028)
#define    AF_STAT_ADDR_LDG_COR_EN                (AF_BASE + 0x002c)
#define    AF_STAT_ADDR_FIR0_G1_G2                (AF_BASE + 0x0030)
#define    AF_STAT_ADDR_FIR0_G3_G4                (AF_BASE + 0x0034)
#define    AF_STAT_ADDR_FIR0_G5                   (AF_BASE + 0x0038)
#define    AF_STAT_ADDR_FIR1_G1_G2                (AF_BASE + 0x003c)
#define    AF_STAT_ADDR_FIR1_G3_G4                (AF_BASE + 0x0040)
#define    AF_STAT_ADDR_FIR1_G5                   (AF_BASE + 0x0044)
#define    AF_STAT_ADDR_IIR0_G1_G3                (AF_BASE + 0x0048)
#define    AF_STAT_ADDR_IIR0_G4_G5                (AF_BASE + 0x004c)
#define    AF_STAT_ADDR_IIR0_G6_G8                (AF_BASE + 0x0050)
#define    AF_STAT_ADDR_IIR0_G9_G10               (AF_BASE + 0x0054)
#define    AF_STAT_ADDR_IIR1_G1_G3                (AF_BASE + 0x0058)
#define    AF_STAT_ADDR_IIR1_G4_G5                (AF_BASE + 0x005c)
#define    AF_STAT_ADDR_IIR1_G6_G8                (AF_BASE + 0x0060)
#define    AF_STAT_ADDR_IIR1_G9_G10               (AF_BASE + 0x0064)
#define    AF_STAT_ADDR_LDG_FIR0_LOW              (AF_BASE + 0x0068)
#define    AF_STAT_ADDR_LDG_FIR0_HIGH             (AF_BASE + 0x006c)
#define    AF_STAT_ADDR_LDG_FIR1_LOW              (AF_BASE + 0x0070)
#define    AF_STAT_ADDR_LDG_FIR1_HIGH             (AF_BASE + 0x0074)
#define    AF_STAT_ADDR_LDG_IIR0_LOW              (AF_BASE + 0x0078)
#define    AF_STAT_ADDR_LDG_IIR0_HIGH             (AF_BASE + 0x007c)
#define    AF_STAT_ADDR_LDG_IIR1_LOW              (AF_BASE + 0x0080)
#define    AF_STAT_ADDR_LDG_IIR1_HIGH             (AF_BASE + 0x0084)
#define    AF_STAT_ADDR_COR_F0_TH_LH              (AF_BASE + 0x0088)
#define    AF_STAT_ADDR_COR_F0_SLP_LIM            (AF_BASE + 0x008c)
#define    AF_STAT_ADDR_COR_F1_TH_LH              (AF_BASE + 0x0090)
#define    AF_STAT_ADDR_COR_F1_SLP_LIM            (AF_BASE + 0x0094)
#define    AF_STAT_ADDR_COR_I0_TH_LH              (AF_BASE + 0x0098)
#define    AF_STAT_ADDR_COR_I0_SLP_LIM            (AF_BASE + 0x009c)
#define    AF_STAT_ADDR_COR_I1_TH_LH              (AF_BASE + 0x00a0)
#define    AF_STAT_ADDR_COR_I1_SLP_LIM            (AF_BASE + 0x00a4)
#define    AF_STAT_ADDR_AF_DMA_BASE_1             (AF_BASE + 0x00a8)
#define    AF_STAT_ADDR_AF_DMA_BASE_2             (AF_BASE + 0x00ac)
#define    AF_STAT_ADDR_AF_DMA_BASE_3             (AF_BASE + 0x00b0)
#define    AF_STAT_ADDR_AF_DMA_BASE_4             (AF_BASE + 0x00b4)
#define    AF_STAT_ADDR_DMA_BASE_NUM              (AF_BASE + 0x00b8)
#define    AF_STAT_ADDR_DMA_INFO                  (AF_BASE + 0x00bc)
#define    AF_STAT_ADDR_DEBUG0                    (AF_BASE + 0x00c0)

//============================================================
// ADR
//============================================================
#define    ADR_ADDR_T_VERSION                     (ADR_BASE + 0x0000)
#define    ADR_ADDR_T_DBG_SEL                     (ADR_BASE + 0x0004)
#define    ADR_ADDR_T_DEG_VALUE                   (ADR_BASE + 0x0008)
#define    ADR_ADDR_STEP_PAR                      (ADR_BASE + 0x000C)
#define    ADR_ADDR_BLK_COORD_M_P_0               (ADR_BASE + 0x0010)
#define    ADR_ADDR_BLK_COORD_M_P_1               (ADR_BASE + 0x0014)
#define    ADR_ADDR_BLK_COORD_M_P_2               (ADR_BASE + 0x0018)
#define    ADR_ADDR_BLK_COORD_N_P_0               (ADR_BASE + 0x001C)
#define    ADR_ADDR_BLK_COORD_N_P_1               (ADR_BASE + 0x0020)
#define    ADR_ADDR_BLK_COORD_N_P_2               (ADR_BASE + 0x0024)
#define    ADR_ADDR_CEN_DIS_P_0                   (ADR_BASE + 0x0028)
#define    ADR_ADDR_CEN_DIS_P_1                   (ADR_BASE + 0x002C)
#define    ADR_ADDR_CEN_DIS_P_2                   (ADR_BASE + 0x0030)
#define    ADR_ADDR_CEN_DIS_P_3                   (ADR_BASE + 0x0034)
#define    ADR_ADDR_CEN_DIS_P_4                   (ADR_BASE + 0x0038)
#define    ADR_ADDR_CEN_DIS_P_5                   (ADR_BASE + 0x003C)
#define    ADR_ADDR_CEN_DIS_P_6                   (ADR_BASE + 0x0040)
#define    ADR_ADDR_CEN_DIS_P_7                   (ADR_BASE + 0x0044)
#define    ADR_ADDR_CEN_DIS_P_8                   (ADR_BASE + 0x0048)
#define    ADR_ADDR_CEN_DIS_P_9                   (ADR_BASE + 0x004C)
#define    ADR_ADDR_CEN_DIS_P_A                   (ADR_BASE + 0x0050)
#define    ADR_ADDR_CEN_DIS_P_B                   (ADR_BASE + 0x0054)
#define    ADR_ADDR_CEN_DIS_P_C                   (ADR_BASE + 0x0058)
#define    ADR_ADDR_CEN_DIS_P_D                   (ADR_BASE + 0x005C)
#define    ADR_ADDR_CEN_DIS_P_E                   (ADR_BASE + 0x0060)
#define    ADR_ADDR_CEN_DIS_P_F                   (ADR_BASE + 0x0064)
#define    ADR_ADDR_MAP_KPOINT_X_P0               (ADR_BASE + 0x0068)
#define    ADR_ADDR_MAP_KPOINT_X_P1               (ADR_BASE + 0x006C)
#define    ADR_ADDR_MAP_KPOINT_X_P2               (ADR_BASE + 0x0070)
#define    ADR_ADDR_MAP_KPOINT_X_P3               (ADR_BASE + 0x0074)
#define    ADR_ADDR_MAP_KPOINT_X_P4               (ADR_BASE + 0x0078)
#define    ADR_ADDR_MAP_KPOINT_X_P5               (ADR_BASE + 0x007C)
#define    ADR_ADDR_MAP_KPOINT_Y_P00_0            (ADR_BASE + 0x0080)
#define    ADR_ADDR_MAP_KPOINT_Y_P00_1            (ADR_BASE + 0x0084)
#define    ADR_ADDR_MAP_KPOINT_Y_P00_2            (ADR_BASE + 0x0088)
#define    ADR_ADDR_MAP_KPOINT_Y_P00_3            (ADR_BASE + 0x008C)
#define    ADR_ADDR_MAP_KPOINT_Y_P00_4            (ADR_BASE + 0x0090)
#define    ADR_ADDR_MAP_KPOINT_Y_P00_5            (ADR_BASE + 0x0094)
#define    ADR_ADDR_MAP_KPOINT_Y_P01_0            (ADR_BASE + 0x0098)
#define    ADR_ADDR_MAP_KPOINT_Y_P01_1            (ADR_BASE + 0x009C)
#define    ADR_ADDR_MAP_KPOINT_Y_P01_2            (ADR_BASE + 0x00A0)
#define    ADR_ADDR_MAP_KPOINT_Y_P01_3            (ADR_BASE + 0x00A4)
#define    ADR_ADDR_MAP_KPOINT_Y_P01_4            (ADR_BASE + 0x00A8)
#define    ADR_ADDR_MAP_KPOINT_Y_P01_5            (ADR_BASE + 0x00AC)
#define    ADR_ADDR_MAP_KPOINT_Y_P02_0            (ADR_BASE + 0x00B0)
#define    ADR_ADDR_MAP_KPOINT_Y_P02_1            (ADR_BASE + 0x00B4)
#define    ADR_ADDR_MAP_KPOINT_Y_P02_2            (ADR_BASE + 0x00B8)
#define    ADR_ADDR_MAP_KPOINT_Y_P02_3            (ADR_BASE + 0x00BC)
#define    ADR_ADDR_MAP_KPOINT_Y_P02_4            (ADR_BASE + 0x00C0)
#define    ADR_ADDR_MAP_KPOINT_Y_P02_5            (ADR_BASE + 0x00C4)
#define    ADR_ADDR_MAP_KPOINT_Y_P03_0            (ADR_BASE + 0x00C8)
#define    ADR_ADDR_MAP_KPOINT_Y_P03_1            (ADR_BASE + 0x00CC)
#define    ADR_ADDR_MAP_KPOINT_Y_P03_2            (ADR_BASE + 0x00D0)
#define    ADR_ADDR_MAP_KPOINT_Y_P03_3            (ADR_BASE + 0x00D4)
#define    ADR_ADDR_MAP_KPOINT_Y_P03_4            (ADR_BASE + 0x00D8)
#define    ADR_ADDR_MAP_KPOINT_Y_P03_5            (ADR_BASE + 0x00DC)
#define    ADR_ADDR_MAP_KPOINT_Y_P04_0            (ADR_BASE + 0x00E0)
#define    ADR_ADDR_MAP_KPOINT_Y_P04_1            (ADR_BASE + 0x00E4)
#define    ADR_ADDR_MAP_KPOINT_Y_P04_2            (ADR_BASE + 0x00E8)
#define    ADR_ADDR_MAP_KPOINT_Y_P04_3            (ADR_BASE + 0x00EC)
#define    ADR_ADDR_MAP_KPOINT_Y_P04_4            (ADR_BASE + 0x00F0)
#define    ADR_ADDR_MAP_KPOINT_Y_P04_5            (ADR_BASE + 0x00F4)
#define    ADR_ADDR_MAP_KPOINT_Y_P05_0            (ADR_BASE + 0x00F8)
#define    ADR_ADDR_MAP_KPOINT_Y_P05_1            (ADR_BASE + 0x00FC)
#define    ADR_ADDR_MAP_KPOINT_Y_P05_2            (ADR_BASE + 0x0100)
#define    ADR_ADDR_MAP_KPOINT_Y_P05_3            (ADR_BASE + 0x0104)
#define    ADR_ADDR_MAP_KPOINT_Y_P05_4            (ADR_BASE + 0x0108)
#define    ADR_ADDR_MAP_KPOINT_Y_P05_5            (ADR_BASE + 0x010C)
#define    ADR_ADDR_MAP_KPOINT_Y_P06_0            (ADR_BASE + 0x0110)
#define    ADR_ADDR_MAP_KPOINT_Y_P06_1            (ADR_BASE + 0x0114)
#define    ADR_ADDR_MAP_KPOINT_Y_P06_2            (ADR_BASE + 0x0118)
#define    ADR_ADDR_MAP_KPOINT_Y_P06_3            (ADR_BASE + 0x011C)
#define    ADR_ADDR_MAP_KPOINT_Y_P06_4            (ADR_BASE + 0x0120)
#define    ADR_ADDR_MAP_KPOINT_Y_P06_5            (ADR_BASE + 0x0124)
#define    ADR_ADDR_MAP_KPOINT_Y_P07_0            (ADR_BASE + 0x0128)
#define    ADR_ADDR_MAP_KPOINT_Y_P07_1            (ADR_BASE + 0x012C)
#define    ADR_ADDR_MAP_KPOINT_Y_P07_2            (ADR_BASE + 0x0130)
#define    ADR_ADDR_MAP_KPOINT_Y_P07_3            (ADR_BASE + 0x0134)
#define    ADR_ADDR_MAP_KPOINT_Y_P07_4            (ADR_BASE + 0x0138)
#define    ADR_ADDR_MAP_KPOINT_Y_P07_5            (ADR_BASE + 0x013C)
#define    ADR_ADDR_MAP_KPOINT_Y_P08_0            (ADR_BASE + 0x0140)
#define    ADR_ADDR_MAP_KPOINT_Y_P08_1            (ADR_BASE + 0x0144)
#define    ADR_ADDR_MAP_KPOINT_Y_P08_2            (ADR_BASE + 0x0148)
#define    ADR_ADDR_MAP_KPOINT_Y_P08_3            (ADR_BASE + 0x014C)
#define    ADR_ADDR_MAP_KPOINT_Y_P08_4            (ADR_BASE + 0x0150)
#define    ADR_ADDR_MAP_KPOINT_Y_P08_5            (ADR_BASE + 0x0154)
#define    ADR_ADDR_MAP_KPOINT_Y_P09_0            (ADR_BASE + 0x0158)
#define    ADR_ADDR_MAP_KPOINT_Y_P09_1            (ADR_BASE + 0x015C)
#define    ADR_ADDR_MAP_KPOINT_Y_P09_2            (ADR_BASE + 0x0160)
#define    ADR_ADDR_MAP_KPOINT_Y_P09_3            (ADR_BASE + 0x0164)
#define    ADR_ADDR_MAP_KPOINT_Y_P09_4            (ADR_BASE + 0x0168)
#define    ADR_ADDR_MAP_KPOINT_Y_P09_5            (ADR_BASE + 0x016C)
#define    ADR_ADDR_MAP_KPOINT_Y_P10_0            (ADR_BASE + 0x0170)
#define    ADR_ADDR_MAP_KPOINT_Y_P10_1            (ADR_BASE + 0x0174)
#define    ADR_ADDR_MAP_KPOINT_Y_P10_2            (ADR_BASE + 0x0178)
#define    ADR_ADDR_MAP_KPOINT_Y_P10_3            (ADR_BASE + 0x017C)
#define    ADR_ADDR_MAP_KPOINT_Y_P10_4            (ADR_BASE + 0x0180)
#define    ADR_ADDR_MAP_KPOINT_Y_P10_5            (ADR_BASE + 0x0184)
#define    ADR_ADDR_MAP_KPOINT_Y_P11_0            (ADR_BASE + 0x0188)
#define    ADR_ADDR_MAP_KPOINT_Y_P11_1            (ADR_BASE + 0x018C)
#define    ADR_ADDR_MAP_KPOINT_Y_P11_2            (ADR_BASE + 0x0190)
#define    ADR_ADDR_MAP_KPOINT_Y_P11_3            (ADR_BASE + 0x0194)
#define    ADR_ADDR_MAP_KPOINT_Y_P11_4            (ADR_BASE + 0x0198)
#define    ADR_ADDR_MAP_KPOINT_Y_P11_5            (ADR_BASE + 0x019C)
#define    ADR_ADDR_MAP_KPOINT_Y_P12_0            (ADR_BASE + 0x01A0)
#define    ADR_ADDR_MAP_KPOINT_Y_P12_1            (ADR_BASE + 0x01A4)
#define    ADR_ADDR_MAP_KPOINT_Y_P12_2            (ADR_BASE + 0x01A8)
#define    ADR_ADDR_MAP_KPOINT_Y_P12_3            (ADR_BASE + 0x01AC)
#define    ADR_ADDR_MAP_KPOINT_Y_P12_4            (ADR_BASE + 0x01B0)
#define    ADR_ADDR_MAP_KPOINT_Y_P12_5            (ADR_BASE + 0x01B4)
#define    ADR_ADDR_MAP_KPOINT_Y_P13_0            (ADR_BASE + 0x01B8)
#define    ADR_ADDR_MAP_KPOINT_Y_P13_1            (ADR_BASE + 0x01BC)
#define    ADR_ADDR_MAP_KPOINT_Y_P13_2            (ADR_BASE + 0x01C0)
#define    ADR_ADDR_MAP_KPOINT_Y_P13_3            (ADR_BASE + 0x01C4)
#define    ADR_ADDR_MAP_KPOINT_Y_P13_4            (ADR_BASE + 0x01C8)
#define    ADR_ADDR_MAP_KPOINT_Y_P13_5            (ADR_BASE + 0x01CC)
#define    ADR_ADDR_MAP_KPOINT_Y_P14_0            (ADR_BASE + 0x01D0)
#define    ADR_ADDR_MAP_KPOINT_Y_P14_1            (ADR_BASE + 0x01D4)
#define    ADR_ADDR_MAP_KPOINT_Y_P14_2            (ADR_BASE + 0x01D8)
#define    ADR_ADDR_MAP_KPOINT_Y_P14_3            (ADR_BASE + 0x01DC)
#define    ADR_ADDR_MAP_KPOINT_Y_P14_4            (ADR_BASE + 0x01E0)
#define    ADR_ADDR_MAP_KPOINT_Y_P14_5            (ADR_BASE + 0x01E4)
#define    ADR_ADDR_MAP_KPOINT_Y_P15_0            (ADR_BASE + 0x01E8)
#define    ADR_ADDR_MAP_KPOINT_Y_P15_1            (ADR_BASE + 0x01EC)
#define    ADR_ADDR_MAP_KPOINT_Y_P15_2            (ADR_BASE + 0x01F0)
#define    ADR_ADDR_MAP_KPOINT_Y_P15_3            (ADR_BASE + 0x01F4)
#define    ADR_ADDR_MAP_KPOINT_Y_P15_4            (ADR_BASE + 0x01F8)
#define    ADR_ADDR_MAP_KPOINT_Y_P15_5            (ADR_BASE + 0x01FC)
#define    ADR_ADDR_MAP_KPOINT_Y_P16_0            (ADR_BASE + 0x0200)
#define    ADR_ADDR_MAP_KPOINT_Y_P16_1            (ADR_BASE + 0x0204)
#define    ADR_ADDR_MAP_KPOINT_Y_P16_2            (ADR_BASE + 0x0208)
#define    ADR_ADDR_MAP_KPOINT_Y_P16_3            (ADR_BASE + 0x020C)
#define    ADR_ADDR_MAP_KPOINT_Y_P16_4            (ADR_BASE + 0x0210)
#define    ADR_ADDR_MAP_KPOINT_Y_P16_5            (ADR_BASE + 0x0214)
#define    ADR_ADDR_MAP_KPOINT_Y_P17_0            (ADR_BASE + 0x0218)
#define    ADR_ADDR_MAP_KPOINT_Y_P17_1            (ADR_BASE + 0x021C)
#define    ADR_ADDR_MAP_KPOINT_Y_P17_2            (ADR_BASE + 0x0220)
#define    ADR_ADDR_MAP_KPOINT_Y_P17_3            (ADR_BASE + 0x0224)
#define    ADR_ADDR_MAP_KPOINT_Y_P17_4            (ADR_BASE + 0x0228)
#define    ADR_ADDR_MAP_KPOINT_Y_P17_5            (ADR_BASE + 0x022C)
#define    ADR_ADDR_MAP_KPOINT_Y_P18_0            (ADR_BASE + 0x0230)
#define    ADR_ADDR_MAP_KPOINT_Y_P18_1            (ADR_BASE + 0x0234)
#define    ADR_ADDR_MAP_KPOINT_Y_P18_2            (ADR_BASE + 0x0238)
#define    ADR_ADDR_MAP_KPOINT_Y_P18_3            (ADR_BASE + 0x023C)
#define    ADR_ADDR_MAP_KPOINT_Y_P18_4            (ADR_BASE + 0x0240)
#define    ADR_ADDR_MAP_KPOINT_Y_P18_5            (ADR_BASE + 0x0244)
#define    ADR_ADDR_MAP_KPOINT_Y_P19_0            (ADR_BASE + 0x0248)
#define    ADR_ADDR_MAP_KPOINT_Y_P19_1            (ADR_BASE + 0x024C)
#define    ADR_ADDR_MAP_KPOINT_Y_P19_2            (ADR_BASE + 0x0250)
#define    ADR_ADDR_MAP_KPOINT_Y_P19_3            (ADR_BASE + 0x0254)
#define    ADR_ADDR_MAP_KPOINT_Y_P19_4            (ADR_BASE + 0x0258)
#define    ADR_ADDR_MAP_KPOINT_Y_P19_5            (ADR_BASE + 0x025C)
#define    ADR_ADDR_WEILUT20_P0                   (ADR_BASE + 0x0260)
#define    ADR_ADDR_WEILUT20_P1                   (ADR_BASE + 0x0264)
#define    ADR_ADDR_WEILUT20_P2                   (ADR_BASE + 0x0268)
#define    ADR_ADDR_WEILUT20_P3                   (ADR_BASE + 0x026C)
#define    ADR_ADDR_WEILUT20_P4                   (ADR_BASE + 0x0270)
#define    ADR_ADDR_WEILUT20_P5                   (ADR_BASE + 0x0274)
#define    ADR_ADDR_WEILUT20_P6                   (ADR_BASE + 0x0278)
#define    ADR_ADDR_WEILUT20_P7                   (ADR_BASE + 0x027C)
#define    ADR_ADDR_WEILUT02_P0                   (ADR_BASE + 0x0280)
#define    ADR_ADDR_WEILUT02_P1                   (ADR_BASE + 0x0284)
#define    ADR_ADDR_WEILUT02_P2                   (ADR_BASE + 0x0288)
#define    ADR_ADDR_WEILUT02_P3                   (ADR_BASE + 0x028C)
#define    ADR_ADDR_WEILUT02_P4                   (ADR_BASE + 0x0290)
#define    ADR_ADDR_WEILUT02_P5                   (ADR_BASE + 0x0294)
#define    ADR_ADDR_WEILUT02_P6                   (ADR_BASE + 0x0298)
#define    ADR_ADDR_WEILUT02_P7                   (ADR_BASE + 0x029C)
#define    ADR_ADDR_WEILUT12_P0                   (ADR_BASE + 0x02A0)
#define    ADR_ADDR_WEILUT12_P1                   (ADR_BASE + 0x02A4)
#define    ADR_ADDR_WEILUT12_P2                   (ADR_BASE + 0x02A8)
#define    ADR_ADDR_WEILUT12_P3                   (ADR_BASE + 0x02AC)
#define    ADR_ADDR_WEILUT12_P4                   (ADR_BASE + 0x02B0)
#define    ADR_ADDR_WEILUT12_P5                   (ADR_BASE + 0x02B4)
#define    ADR_ADDR_WEILUT12_P6                   (ADR_BASE + 0x02B8)
#define    ADR_ADDR_WEILUT12_P7                   (ADR_BASE + 0x02BC)
#define    ADR_ADDR_WEILUT22_P0                   (ADR_BASE + 0x02C0)
#define    ADR_ADDR_WEILUT22_P1                   (ADR_BASE + 0x02C4)
#define    ADR_ADDR_WEILUT22_P2                   (ADR_BASE + 0x02C8)
#define    ADR_ADDR_WEILUT22_P3                   (ADR_BASE + 0x02CC)
#define    ADR_ADDR_WEILUT22_P4                   (ADR_BASE + 0x02D0)
#define    ADR_ADDR_WEILUT22_P5                   (ADR_BASE + 0x02D4)
#define    ADR_ADDR_WEILUT22_P6                   (ADR_BASE + 0x02D8)
#define    ADR_ADDR_WEILUT22_P7                   (ADR_BASE + 0x02DC)
#define    ADR_ADDR_WEILUT21_P0                   (ADR_BASE + 0x02E0)
#define    ADR_ADDR_WEILUT21_P1                   (ADR_BASE + 0x02E4)
#define    ADR_ADDR_WEILUT21_P2                   (ADR_BASE + 0x02E8)
#define    ADR_ADDR_WEILUT21_P3                   (ADR_BASE + 0x02EC)
#define    ADR_ADDR_WEILUT21_P4                   (ADR_BASE + 0x02F0)
#define    ADR_ADDR_WEILUT21_P5                   (ADR_BASE + 0x02F4)
#define    ADR_ADDR_WEILUT21_P6                   (ADR_BASE + 0x02F8)
#define    ADR_ADDR_WEILUT21_P7                   (ADR_BASE + 0x02FC)
#define    ADR_ADDR_MAP_KPOINT_POW_P0             (ADR_BASE + 0x0300)
#define    ADR_ADDR_MAP_KPOINT_POW_P1             (ADR_BASE + 0x0304)
#define    ADR_ADDR_MAP_KPOINT_POW_P2             (ADR_BASE + 0x0308)
#define    ADR_ADDR_CTC_KPOINT_X_P0               (ADR_BASE + 0x0310)
#define    ADR_ADDR_CTC_KPOINT_X_P1               (ADR_BASE + 0x0314)
#define    ADR_ADDR_CON_W_DIS_P00                 (ADR_BASE + 0x0320)
#define    ADR_ADDR_CON_W_DIS_P01                 (ADR_BASE + 0x0324)
#define    ADR_ADDR_CON_W_DIS_P02                 (ADR_BASE + 0x0328)
#define    ADR_ADDR_CON_W_DIS_P03                 (ADR_BASE + 0x032C)
#define    ADR_ADDR_CON_W_DIS_P04                 (ADR_BASE + 0x0330)
#define    ADR_ADDR_CON_W_DIS_P05                 (ADR_BASE + 0x0334)
#define    ADR_ADDR_CON_W_DIS_P06                 (ADR_BASE + 0x0338)
#define    ADR_ADDR_CON_W_DIS_P07                 (ADR_BASE + 0x033C)
#define    ADR_ADDR_CON_W_DIS_P08                 (ADR_BASE + 0x0340)
#define    ADR_ADDR_CON_W_DIS_P09                 (ADR_BASE + 0x0344)
#define    ADR_ADDR_CON_W_DIS_P10                 (ADR_BASE + 0x0348)
#define    ADR_ADDR_CON_W_DIS_P11                 (ADR_BASE + 0x034C)
#define    ADR_ADDR_CON_W_DIS_P12                 (ADR_BASE + 0x0350)
#define    ADR_ADDR_CON_W_DIS_P13                 (ADR_BASE + 0x0354)
#define    ADR_ADDR_CON_W_DIS_P14                 (ADR_BASE + 0x0358)
#define    ADR_ADDR_CON_W_DIS_P15                 (ADR_BASE + 0x035C)
#define    ADR_ADDR_CON_W_DIS_P16                 (ADR_BASE + 0x0360)
#define    ADR_ADDR_CON_W_DIS_P17                 (ADR_BASE + 0x0364)
#define    ADR_ADDR_CON_W_DIS_P18                 (ADR_BASE + 0x0368)
#define    ADR_ADDR_CON_W_DIS_P19                 (ADR_BASE + 0x036C)
#define    ADR_ADDR_CON_W_DIS_P20                 (ADR_BASE + 0x0370)
#define    ADR_ADDR_CON_W_DIS_P21                 (ADR_BASE + 0x0374)
#define    ADR_ADDR_CON_W_DIS_P22                 (ADR_BASE + 0x0378)
#define    ADR_ADDR_CON_W_DIS_P23                 (ADR_BASE + 0x037C)
#define    ADR_ADDR_CON_W_DIS_P24                 (ADR_BASE + 0x0380)
#define    ADR_ADDR_CON_W_DIS_P25                 (ADR_BASE + 0x0384)
#define    ADR_ADDR_CON_W_DIS_P26                 (ADR_BASE + 0x0388)
#define    ADR_ADDR_CON_W_DIS_P27                 (ADR_BASE + 0x038C)
#define    ADR_ADDR_CON_W_DIS_P28                 (ADR_BASE + 0x0390)
#define    ADR_ADDR_CON_W_DIS_P29                 (ADR_BASE + 0x0394)
#define    ADR_ADDR_CON_W_DIS_P30                 (ADR_BASE + 0x0398)
#define    ADR_ADDR_CON_W_DIS_P31                 (ADR_BASE + 0x039C)
#define    ADR_ADDR_CTC_KPOINT_MUX_P0             (ADR_BASE + 0x03A0)
#define    ADR_ADDR_CTC_KPOINT_MUX_P1             (ADR_BASE + 0x03A4)
#define    ADR_ADDR_CTC_RATIO                     (ADR_BASE + 0x03A8)
#define    ADR_ADDR_MIN_KPOINT_X_P0               (ADR_BASE + 0x03B0)
#define    ADR_ADDR_MIN_KPOINT_X_P1               (ADR_BASE + 0x03B4)
#define    ADR_ADDR_MIN_KPOINT_X_P2               (ADR_BASE + 0x03B8)
#define    ADR_ADDR_MIN_KPOINT_X_P3               (ADR_BASE + 0x03BC)
#define    ADR_ADDR_MIN_KPOINT_X_P4               (ADR_BASE + 0x03C0)
#define    ADR_ADDR_MIN_KPOINT_X_P5               (ADR_BASE + 0x03C4)
#define    ADR_ADDR_MIN_KPOINT_Y_P0               (ADR_BASE + 0x03C8)
#define    ADR_ADDR_MIN_KPOINT_Y_P1               (ADR_BASE + 0x03CC)
#define    ADR_ADDR_MIN_KPOINT_Y_P2               (ADR_BASE + 0x03D0)
#define    ADR_ADDR_MIN_KPOINT_Y_P3               (ADR_BASE + 0x03D4)
#define    ADR_ADDR_MIN_KPOINT_Y_P4               (ADR_BASE + 0x03D8)
#define    ADR_ADDR_MIN_KPOINT_Y_P5               (ADR_BASE + 0x03DC)
#define    ADR_ADDR_MIN_KPOINT_POW_P0             (ADR_BASE + 0x03E0)
#define    ADR_ADDR_MIN_KPOINT_POW_P1             (ADR_BASE + 0x03E4)
#define    ADR_ADDR_MIN_KPOINT_POW_P2             (ADR_BASE + 0x03E8)
#define    ADR_ADDR_COC_KPOINT_X_P0               (ADR_BASE + 0x03F0)
#define    ADR_ADDR_COC_KPOINT_X_P1               (ADR_BASE + 0x03F4)
#define    ADR_ADDR_COC_KPOINT_X_P2               (ADR_BASE + 0x03F8)
#define    ADR_ADDR_COC_KPOINT_X_P3               (ADR_BASE + 0x03FC)
#define    ADR_ADDR_COC_KPOINT_X_P4               (ADR_BASE + 0x0400)
#define    ADR_ADDR_COC_KPOINT_X_P5               (ADR_BASE + 0x0404)
#define    ADR_ADDR_COC_THRES                     (ADR_BASE + 0x0408)
#define    ADR_ADDR_COC_STREN                     (ADR_BASE + 0x040C)
#define    ADR_ADDR_COC_MODE                      (ADR_BASE + 0x0410)
#define    ADR_ADDR_COC_KPOINT_POW_P0             (ADR_BASE + 0x0414)
#define    ADR_ADDR_COC_KPOINT_POW_P1             (ADR_BASE + 0x0418)
#define    ADR_ADDR_COC_KPOINT_POW_P2             (ADR_BASE + 0x041C)
#define    ADR_ADDR_STAT_BLOCK_DIFF_P_0           (ADR_BASE + 0x0420)
#define    ADR_ADDR_STAT_BLOCK_DIFF_P_1           (ADR_BASE + 0x0424)
#define    ADR_ADDR_BANK_ADDR_P0                  (ADR_BASE + 0x0428)
#define    ADR_ADDR_BANK_ADDR_P1                  (ADR_BASE + 0x042C)
#define    ADR_ADDR_BANK_ADDR_P2                  (ADR_BASE + 0x0430)
#define    ADR_ADDR_BANK_ADDR_P3                  (ADR_BASE + 0x0434)
#define    ADR_ADDR_BANK_NUMBER                   (ADR_BASE + 0x0438)
#define    ADR_ADDR_FRAME_ADDR                    (ADR_BASE + 0x043C)
#define    ADR_ADDR_FRAME_ID                      (ADR_BASE + 0x0440)
#define    ADR_ADDR_FRAME_RATE                    (ADR_BASE + 0x0444)
#define    ADR_ADDR_SHADOW_CTRL                   (ADR_BASE + 0x0448)
#define    ADR_ADDR_DEBUG_SIGNAL_0                (ADR_BASE + 0x0450)
#define    ADR_ADDR_DEBUG_SIGNAL_1                (ADR_BASE + 0x0454)
#define    ADR_ADDR_DEBUG_SIGNAL_2                (ADR_BASE + 0x0458)
#define    ADR_ADDR_DEBUG_SIGNAL_3                (ADR_BASE + 0x045C)
#define    ADR_ADDR_DEBUG_SIGNAL_4                (ADR_BASE + 0x0460)
#define    ADR_ADDR_DEBUG_SIGNAL_5                (ADR_BASE + 0x0464)

//============================================================
// IRINT
//============================================================
#define    IRINT_ADDR_T_VERSION                   (IRINT_BASE + 0x0000)
#define    IRINT_ADDR_T_DBG_SEL                   (IRINT_BASE + 0x0004)
#define    IRINT_ADDR_T_DBG_VALUE                 (IRINT_BASE + 0x0008)
#define    IRINT_ADDR_DIFF_PAR                    (IRINT_BASE + 0x0010)
#define    IRINT_ADDR_MIN_PAR                     (IRINT_BASE + 0x0014)

//============================================================
// DMSC
//============================================================
#define    DMSC_ADDR_SYNC                         (DMSC_BASE + 0x0000)
#define    DMSC_ADDR_G_STD_STREN                  (DMSC_BASE + 0x0004)
#define    DMSC_ADDR_UU_THRES                     (DMSC_BASE + 0x0008)
#define    DMSC_ADDR_ALIAS_DIR_DIFF               (DMSC_BASE + 0x000C)
#define    DMSC_ADDR_WIN5_HV_EDGE_THRES           (DMSC_BASE + 0x0010)
#define    DMSC_ADDR_HV_EDGE_THRES                (DMSC_BASE + 0x0014)
#define    DMSC_ADDR_HV_EDGE                      (DMSC_BASE + 0x0020)
#define    DMSC_ADDR_AA_EDGE_THRES                (DMSC_BASE + 0x0024)
#define    DMSC_ADDR_AA_EDGE                      (DMSC_BASE + 0x0028)
#define    DMSC_ADDR_HVAA_EDGE_THRES              (DMSC_BASE + 0x002C)
#define    DMSC_ADDR_HVAA_EDGE                    (DMSC_BASE + 0x0030)
#define    DMSC_ADDR_ALIAS_STREN                  (DMSC_BASE + 0x0034)
#define    DMSC_ADDR_ALIAS_THRES                  (DMSC_BASE + 0x0038)
#define    DMSC_ADDR_NOR_ALIAS_BLUR               (DMSC_BASE + 0x003C)
#define    DMSC_ADDR_NOR_UU_WEI_STREN             (DMSC_BASE + 0x0040)
#define    DMSC_ADDR_SP_D_V2_SIGMA                (DMSC_BASE + 0x0044)
#define    DMSC_ADDR_SP_D_W_SP_STREN              (DMSC_BASE + 0x0048)
#define    DMSC_ADDR_SP_D_LL_STREN                (DMSC_BASE + 0x004C)
#define    DMSC_ADDR_SP_D_LL_THRES                (DMSC_BASE + 0x0050)
#define    DMSC_ADDR_SP_D_W_LIMIT                 (DMSC_BASE + 0x0054)
#define    DMSC_ADDR_SP_D_B_LIMIT                 (DMSC_BASE + 0x0058)
#define    DMSC_ADDR_SP_UD_V2_SIGMA               (DMSC_BASE + 0x005C)
#define    DMSC_ADDR_SP_UD_W_SP_STREN             (DMSC_BASE + 0x0060)
#define    DMSC_ADDR_SP_UD_LL_STREN               (DMSC_BASE + 0x0064)
#define    DMSC_ADDR_SP_UD_LL_THRES               (DMSC_BASE + 0x0068)
#define    DMSC_ADDR_SP_UD_W_LIMIT                (DMSC_BASE + 0x006C)
#define    DMSC_ADDR_SP_UD_B_LIMIT                (DMSC_BASE + 0x0070)
#define    DMSC_ADDR_SP_NOR_ALIAS_THRES           (DMSC_BASE + 0x0074)
#define    DMSC_ADDR_ALIAS_FUSION_THRES           (DMSC_BASE + 0x0078)
#define    DMSC_ADDR_ALIAS_DIR_INTP_SP_STREN      (DMSC_BASE + 0x007C)
#define    DMSC_ADDR_FC_ALIAS_STREN               (DMSC_BASE + 0x0080)
#define    DMSC_ADDR_FC_ALIAS_THRES               (DMSC_BASE + 0x0084)
#define    DMSC_ADDR_FC_NOR_SAT_THRES             (DMSC_BASE + 0x0088)
#define    DMSC_ADDR_FC_TEXT_THRES                (DMSC_BASE + 0x008C)
#define    DMSC_ADDR_FC_NOR_EDGE_SLOPE            (DMSC_BASE + 0x0090)
#define    DMSC_ADDR_UU_NP_ARRAY_RG0              (DMSC_BASE + 0x0094)
#define    DMSC_ADDR_UU_NP_ARRAY_RG1              (DMSC_BASE + 0x0098)
#define    DMSC_ADDR_UU_NP_ARRAY_RG2              (DMSC_BASE + 0x009C)
#define    DMSC_ADDR_UU_NP_ARRAY_RG3              (DMSC_BASE + 0x00A0)
#define    DMSC_ADDR_UU_NP_ARRAY_RG4              (DMSC_BASE + 0x00A4)
#define    DMSC_ADDR_UU_NP_ARRAY_RG5              (DMSC_BASE + 0x00A8)
#define    DMSC_ADDR_UU_NP_ARRAY_RG6              (DMSC_BASE + 0x00AC)
#define    DMSC_ADDR_UU_NP_ARRAY_RG7              (DMSC_BASE + 0x00B0)
#define    DMSC_ADDR_SP_D_SIGMA_3_NP_ARRAY_RG0    (DMSC_BASE + 0x00B4)
#define    DMSC_ADDR_SP_D_SIGMA_3_NP_ARRAY_RG1    (DMSC_BASE + 0x00B8)
#define    DMSC_ADDR_SP_D_SIGMA_3_NP_ARRAY_RG2    (DMSC_BASE + 0x00BC)
#define    DMSC_ADDR_SP_D_W_WEI_NP_ARRAY_RG0      (DMSC_BASE + 0x00C0)
#define    DMSC_ADDR_SP_D_W_WEI_NP_ARRAY_RG1      (DMSC_BASE + 0x00C4)
#define    DMSC_ADDR_SP_D_W_WEI_NP_ARRAY_RG2      (DMSC_BASE + 0x00C8)
#define    DMSC_ADDR_SP_D_W_WEI_NP_ARRAY_RG3      (DMSC_BASE + 0x00CC)
#define    DMSC_ADDR_SP_D_B_WEI_NP_ARRAY_RG0      (DMSC_BASE + 0x00D0)
#define    DMSC_ADDR_SP_D_B_WEI_NP_ARRAY_RG1      (DMSC_BASE + 0x00D4)
#define    DMSC_ADDR_SP_D_B_WEI_NP_ARRAY_RG2      (DMSC_BASE + 0x00D8)
#define    DMSC_ADDR_SP_D_B_WEI_NP_ARRAY_RG3      (DMSC_BASE + 0x00DC)
#define    DMSC_ADDR_SP_UD_W_WEI_NP_ARRAY_RG0     (DMSC_BASE + 0x00E0)
#define    DMSC_ADDR_SP_UD_W_WEI_NP_ARRAY_RG1     (DMSC_BASE + 0x00E4)
#define    DMSC_ADDR_SP_UD_W_WEI_NP_ARRAY_RG2     (DMSC_BASE + 0x00E8)
#define    DMSC_ADDR_SP_UD_W_WEI_NP_ARRAY_RG3     (DMSC_BASE + 0x00EC)
#define    DMSC_ADDR_SP_UD_B_WEI_NP_ARRAY_RG0     (DMSC_BASE + 0x00F0)
#define    DMSC_ADDR_SP_UD_B_WEI_NP_ARRAY_RG1     (DMSC_BASE + 0x00F4)
#define    DMSC_ADDR_SP_UD_B_WEI_NP_ARRAY_RG2     (DMSC_BASE + 0x00F8)
#define    DMSC_ADDR_SP_UD_B_WEI_NP_ARRAY_RG3     (DMSC_BASE + 0x00FC)
#define    DMSC_ADDR_OUT_OPT                      (DMSC_BASE + 0x0100)
#define    DMSC_ADDR_SP_DEBUG_REG_0               (DMSC_BASE + 0x0104)
#define    DMSC_ADDR_SP_DEBUG_REG_1               (DMSC_BASE + 0x0108)
#define    DMSC_ADDR_FC_TEXT_2_STREN              (DMSC_BASE + 0x010C)
#define    DMSC_ADDR_FC_TEXT_2_THRES              (DMSC_BASE + 0x0110)
#define    DMSC_ADDR_FC_THRES_H_1                 (DMSC_BASE + 0x0114)
#define    DMSC_ADDR_FC_THRES_H_2                 (DMSC_BASE + 0x0118)

//============================================================
// CCM
//============================================================
#define    CCM_ADDR_REG_CTRL                      (CCM_BASE + 0x0000)
#define    CCM_ADDR_CCM_RRRG                      (CCM_BASE + 0x0004)
#define    CCM_ADDR_CCM_RBGR                      (CCM_BASE + 0x0008)
#define    CCM_ADDR_CCM_GGGB                      (CCM_BASE + 0x000c)
#define    CCM_ADDR_CCM_BRBG                      (CCM_BASE + 0x0010)
#define    CCM_ADDR_CCM_BB                        (CCM_BASE + 0x0014)
#define    CCM_ADDR_DP_CFG                        (CCM_BASE + 0x0018)
#define    CCM_ADDR_DP_SLOP                       (CCM_BASE + 0x001c)
#define    CCM_ADDR_SAT_THRES                     (CCM_BASE + 0x0020)

//===============================================
// DEFOG
//===============================================
#define    DEFOG_ADDR_BLOCK_COORD_M_01_00         (DEFOG_BASE + 0x0000)
#define    DEFOG_ADDR_BLOCK_COORD_M_03_02         (DEFOG_BASE + 0x0004)
#define    DEFOG_ADDR_BLOCK_COORD_M_05_04         (DEFOG_BASE + 0x0008)
#define    DEFOG_ADDR_BLOCK_COORD_M_07_06         (DEFOG_BASE + 0x000C)
#define    DEFOG_ADDR_BLOCK_COORD_M_09_08         (DEFOG_BASE + 0x0010)
#define    DEFOG_ADDR_BLOCK_COORD_M____10         (DEFOG_BASE + 0x0014)
#define    DEFOG_ADDR_BLOCK_COORD_N_01_00         (DEFOG_BASE + 0x0020)
#define    DEFOG_ADDR_BLOCK_COORD_N_03_02         (DEFOG_BASE + 0x0024)
#define    DEFOG_ADDR_BLOCK_COORD_N_05_04         (DEFOG_BASE + 0x0028)
#define    DEFOG_ADDR_BLOCK_COORD_N_07_06         (DEFOG_BASE + 0x002C)
#define    DEFOG_ADDR_BLOCK_COORD_N_09_08         (DEFOG_BASE + 0x0030)
#define    DEFOG_ADDR_BLOCK_COORD_N_11_10         (DEFOG_BASE + 0x0034)
#define    DEFOG_ADDR_BLOCK_COORD_N_13_12         (DEFOG_BASE + 0x0038)
#define    DEFOG_ADDR_BLOCK_COORD_N_15_14         (DEFOG_BASE + 0x003C)
#define    DEFOG_ADDR_BLOCK_COORD_N_17_16         (DEFOG_BASE + 0x0040)
#define    DEFOG_ADDR_BLOCK_COORD_N_19_18         (DEFOG_BASE + 0x0044)
#define    DEFOG_ADDR_BLOCK_COORD_N____20         (DEFOG_BASE + 0x0048)
#define    DEFOG_ADDR_CT3X3_DIS_01_00             (DEFOG_BASE + 0x0050)
#define    DEFOG_ADDR_CT3X3_DIS_03_02             (DEFOG_BASE + 0x0054)
#define    DEFOG_ADDR_CT3X3_DIS_05_04             (DEFOG_BASE + 0x0058)
#define    DEFOG_ADDR_CT3X3_DIS_07_06             (DEFOG_BASE + 0x005C)
#define    DEFOG_ADDR_CT3X3_DIS_09_08             (DEFOG_BASE + 0x0060)
#define    DEFOG_ADDR_CT3X3_DIS_11_10             (DEFOG_BASE + 0x0064)
#define    DEFOG_ADDR_CT3X3_DIS_13_12             (DEFOG_BASE + 0x0068)
#define    DEFOG_ADDR_CT3X3_DIS_15_14             (DEFOG_BASE + 0x006C)
#define    DEFOG_ADDR_CT3X3_DIS_17_16             (DEFOG_BASE + 0x0070)
#define    DEFOG_ADDR_CT3X3_DIS_19_18             (DEFOG_BASE + 0x0074)
#define    DEFOG_ADDR_CT3X3_DIS_21_20             (DEFOG_BASE + 0x0078)
#define    DEFOG_ADDR_CT3X3_DIS_23_22             (DEFOG_BASE + 0x007C)
#define    DEFOG_ADDR_CT5X5_DIS_01_00             (DEFOG_BASE + 0x0080)
#define    DEFOG_ADDR_CT5X5_DIS_03_02             (DEFOG_BASE + 0x0084)
#define    DEFOG_ADDR_CT5X5_DIS_05_04             (DEFOG_BASE + 0x0088)
#define    DEFOG_ADDR_CT5X5_DIS_07_06             (DEFOG_BASE + 0x008C)
#define    DEFOG_ADDR_CT5X5_DIS_09_08             (DEFOG_BASE + 0x0090)
#define    DEFOG_ADDR_CT5X5_DIS_11_10             (DEFOG_BASE + 0x0094)
#define    DEFOG_ADDR_CT5X5_DIS_13_12             (DEFOG_BASE + 0x0098)
#define    DEFOG_ADDR_CT5X5_DIS_15_14             (DEFOG_BASE + 0x009C)
#define    DEFOG_ADDR_CT5X5_DIS_17_16             (DEFOG_BASE + 0x00A0)
#define    DEFOG_ADDR_CT5X5_DIS_19_18             (DEFOG_BASE + 0x00A4)
#define    DEFOG_ADDR_CT5X5_DIS_21_20             (DEFOG_BASE + 0x00A8)
#define    DEFOG_ADDR_CT5X5_DIS_23_22             (DEFOG_BASE + 0x00AC)
#define    DEFOG_ADDR_CT5X5_DIS_25_24             (DEFOG_BASE + 0x00B0)
#define    DEFOG_ADDR_CT5X5_DIS_27_26             (DEFOG_BASE + 0x00B4)
#define    DEFOG_ADDR_CT5X5_DIS_29_28             (DEFOG_BASE + 0x00B8)
#define    DEFOG_ADDR_CT5X5_DIS_31_30             (DEFOG_BASE + 0x00BC)
#define    DEFOG_ADDR_WEIGHTLUT02_05_00           (DEFOG_BASE + 0x00C0)
#define    DEFOG_ADDR_WEIGHTLUT02_11_06           (DEFOG_BASE + 0x00C4)
#define    DEFOG_ADDR_WEIGHTLUT02_17_12           (DEFOG_BASE + 0x00C8)
#define    DEFOG_ADDR_WEIGHTLUT02_23_18           (DEFOG_BASE + 0x00CC)
#define    DEFOG_ADDR_WEIGHTLUT02_29_24           (DEFOG_BASE + 0x00D0)
#define    DEFOG_ADDR_WEIGHTLUT02_31_30           (DEFOG_BASE + 0x00D4)
#define    DEFOG_ADDR_WEIGHTLUT20_05_00           (DEFOG_BASE + 0x00E0)
#define    DEFOG_ADDR_WEIGHTLUT20_11_06           (DEFOG_BASE + 0x00E4)
#define    DEFOG_ADDR_WEIGHTLUT20_17_12           (DEFOG_BASE + 0x00E8)
#define    DEFOG_ADDR_WEIGHTLUT20_23_18           (DEFOG_BASE + 0x00EC)
#define    DEFOG_ADDR_WEIGHTLUT20_29_24           (DEFOG_BASE + 0x00F0)
#define    DEFOG_ADDR_WEIGHTLUT20_31_30           (DEFOG_BASE + 0x00F4)
#define    DEFOG_ADDR_WEIGHTLUT21_05_00           (DEFOG_BASE + 0x0100)
#define    DEFOG_ADDR_WEIGHTLUT21_11_06           (DEFOG_BASE + 0x0104)
#define    DEFOG_ADDR_WEIGHTLUT21_17_12           (DEFOG_BASE + 0x0108)
#define    DEFOG_ADDR_WEIGHTLUT21_23_18           (DEFOG_BASE + 0x010C)
#define    DEFOG_ADDR_WEIGHTLUT21_29_24           (DEFOG_BASE + 0x0110)
#define    DEFOG_ADDR_WEIGHTLUT21_31_30           (DEFOG_BASE + 0x0114)
#define    DEFOG_ADDR_WEIGHTLUT12_05_00           (DEFOG_BASE + 0x0120)
#define    DEFOG_ADDR_WEIGHTLUT12_11_06           (DEFOG_BASE + 0x0124)
#define    DEFOG_ADDR_WEIGHTLUT12_17_12           (DEFOG_BASE + 0x0128)
#define    DEFOG_ADDR_WEIGHTLUT12_23_18           (DEFOG_BASE + 0x012C)
#define    DEFOG_ADDR_WEIGHTLUT12_29_24           (DEFOG_BASE + 0x0130)
#define    DEFOG_ADDR_WEIGHTLUT12_31_30           (DEFOG_BASE + 0x0134)
#define    DEFOG_ADDR_WEIGHTLUT22_05_00           (DEFOG_BASE + 0x0140)
#define    DEFOG_ADDR_WEIGHTLUT22_11_06           (DEFOG_BASE + 0x0144)
#define    DEFOG_ADDR_WEIGHTLUT22_17_12           (DEFOG_BASE + 0x0148)
#define    DEFOG_ADDR_WEIGHTLUT22_23_18           (DEFOG_BASE + 0x014C)
#define    DEFOG_ADDR_WEIGHTLUT22_29_24           (DEFOG_BASE + 0x0150)
#define    DEFOG_ADDR_WEIGHTLUT22_31_30           (DEFOG_BASE + 0x0154)
#define    DEFOG_ADDR_BANK_BUFF_NUM               (DEFOG_BASE + 0x0160)
#define    DEFOG_ADDR_BANK_ADDR_0                 (DEFOG_BASE + 0x0164)
#define    DEFOG_ADDR_BANK_ADDR_1                 (DEFOG_BASE + 0x0168)
#define    DEFOG_ADDR_BANK_ADDR_2                 (DEFOG_BASE + 0x016C)
#define    DEFOG_ADDR_BANK_ADDR_3                 (DEFOG_BASE + 0x0170)
#define    DEFOG_ADDR_PARA                        (DEFOG_BASE + 0x0180)
#define    DEFOG_ADDR_CLOR_CTRL_X3210             (DEFOG_BASE + 0x0190)
#define    DEFOG_ADDR_CLOR_CTRL_Y3210             (DEFOG_BASE + 0x0194)
#define    DEFOG_ADDR_CLOR_CTRL_XY44              (DEFOG_BASE + 0x0198)
#define    DEFOG_ADDR_CLOR_CTRL_POW3210           (DEFOG_BASE + 0x019C)
#define    DEFOG_ADDR_TRANS_DARK_CTRL_X3210       (DEFOG_BASE + 0x01A0)
#define    DEFOG_ADDR_TRANS_DARK_CTRL_Y3210       (DEFOG_BASE + 0x01A4)
#define    DEFOG_ADDR_TRANS_DARK_CTRL_XY44        (DEFOG_BASE + 0x01A8)
#define    DEFOG_ADDR_TRANS_DARK_CTRL_POW3210     (DEFOG_BASE + 0x01AC)
#define    DEFOG_ADDR_OVEREXPO_WGT_X3210          (DEFOG_BASE + 0x01B0)
#define    DEFOG_ADDR_OVEREXPO_WGT_Y3210          (DEFOG_BASE + 0x01B4)
#define    DEFOG_ADDR_OVEREXPO_WGT_POW210         (DEFOG_BASE + 0x01B8)
#define    DEFOG_ADDR_DARKSPC_WGT_X3210           (DEFOG_BASE + 0x01C0)
#define    DEFOG_ADDR_DARKSPC_WGT_Y3210           (DEFOG_BASE + 0x01C4)
#define    DEFOG_ADDR_DARKSPC_WGT_POW210          (DEFOG_BASE + 0x01C8)
#define    DEFOG_ADDR_FRAME_RATE                  (DEFOG_BASE + 0x01D0)
#define    DEFOG_ADDR_CTRL                        (DEFOG_BASE + 0x01E0)
#define    DEFOG_ADDR_FRAME_ADDR                  (DEFOG_BASE + 0x0200)
#define    DEFOG_ADDR_FRAME_ID                    (DEFOG_BASE + 0x0204)
#define    DEFOG_ADDR_DEBUG_SIGNAL_0              (DEFOG_BASE + 0x0208)
#define    DEFOG_ADDR_DEBUG_SIGNAL_1              (DEFOG_BASE + 0x020C)
#define    DEFOG_ADDR_DEBUG_SIGNAL_2              (DEFOG_BASE + 0x0210)
#define    DEFOG_ADDR_DEBUG_SIGNAL_3              (DEFOG_BASE + 0x0214)
#define    DEFOG_ADDR_DEBUG_SIGNAL_4              (DEFOG_BASE + 0x0218)
#define    DEFOG_ADDR_BLOCK_CFG_SEL		  (DEFOG_BASE + 0x0220)
#define	   DEFOG_ADDR_BLOCK_CFG_BASE		  (DEFOG_BASE + 0x0224)

//============================================================
// CSC
//============================================================
#define    CSC_ADDR_CTRL                          (CSC_BASE + 0x0000)
#define    CSC_ADDR_SUB                           (CSC_BASE + 0x0004)
#define    CSC_ADDR_PAR_0                         (CSC_BASE + 0x0010)
#define    CSC_ADDR_PAR_1                         (CSC_BASE + 0x0014)
#define    CSC_ADDR_PAR_2                         (CSC_BASE + 0x0018)
#define    CSC_ADDR_OFF_SET                       (CSC_BASE + 0x0020)
#define    CSC_ADDR_CLIP                          (CSC_BASE + 0x0030)

//============================================================
// CLM
//============================================================
#define    CLM_ADDR_REG_CTRL                      (CLM_BASE + 0x0000)
#define    CLM_ADDR_LUT_SHIFT                     (CLM_BASE + 0x0004)
#define    CLM_ADDR_CSC_RB                        (CLM_BASE + 0x0008)
#define    CLM_ADDR_CSC_G                         (CLM_BASE + 0x000c)
#define    CLM_ADDR_CSC_U                         (CLM_BASE + 0x0010)
#define    CLM_ADDR_CSC_V                         (CLM_BASE + 0x0014)
#define    CLM_ADDR_CSC_Y                         (CLM_BASE + 0x0018)
#define    CLM_ADDR_CA_S_THRES                    (CLM_BASE + 0x001c)
#define    CLM_ADDR_CA_S_SLOP                     (CLM_BASE + 0x0020)
#define    CLM_ADDR_CA_V_THRES                    (CLM_BASE + 0x0024)
#define    CLM_ADDR_CA_V_SLOP                     (CLM_BASE + 0x0028)
#define    CLM_ADDR_DEBUG0                        (CLM_BASE + 0x002c)

//============================================================
// Sharpen
//============================================================
#define    SHARPEN_ADDR_SYNC                  (SP_BASE + 0x0000)
#define    SHARPEN_ADDR_STD_DIV_OPT           (SP_BASE + 0x0004)
#define    SHARPEN_ADDR_V2_SIGMA              (SP_BASE + 0x0008)
#define    SHARPEN_ADDR_W_WEI_SEG_OPT         (SP_BASE + 0x000C)
#define    SHARPEN_ADDR_STREN                 (SP_BASE + 0x0010)
#define    SHARPEN_ADDR_THRES                 (SP_BASE + 0x0014)
#define    SHARPEN_ADDR_UU_SLOPE              (SP_BASE + 0x0018)
#define    SHARPEN_ADDR_UU_NP_ARRAY_RG0       (SP_BASE + 0x001C)
#define    SHARPEN_ADDR_UU_NP_ARRAY_RG1       (SP_BASE + 0x0020)
#define    SHARPEN_ADDR_UU_NP_ARRAY_RG2       (SP_BASE + 0x0024)
#define    SHARPEN_ADDR_UU_NP_ARRAY_RG3       (SP_BASE + 0x0028)
#define    SHARPEN_ADDR_V1_SIGMA_NP_ARRAY_RG0 (SP_BASE + 0x002C)
#define    SHARPEN_ADDR_V1_SIGMA_NP_ARRAY_RG1 (SP_BASE + 0x0030)
#define    SHARPEN_ADDR_V1_SIGMA_NP_ARRAY_RG2 (SP_BASE + 0x0034)
#define    SHARPEN_ADDR_W_WEI_NP_ARRAY_RG0    (SP_BASE + 0x0038)
#define    SHARPEN_ADDR_W_WEI_NP_ARRAY_RG1    (SP_BASE + 0x003C)
#define    SHARPEN_ADDR_W_WEI_NP_ARRAY_RG2    (SP_BASE + 0x0040)
#define    SHARPEN_ADDR_W_WEI_NP_ARRAY_RG3    (SP_BASE + 0x0044)
#define    SHARPEN_ADDR_B_WEI_NP_ARRAY_RG0    (SP_BASE + 0x0048)
#define    SHARPEN_ADDR_B_WEI_NP_ARRAY_RG1    (SP_BASE + 0x004C)
#define    SHARPEN_ADDR_B_WEI_NP_ARRAY_RG2    (SP_BASE + 0x0050)
#define    SHARPEN_ADDR_B_WEI_NP_ARRAY_RG3    (SP_BASE + 0x0054)

//============================================================
// MDNS
//============================================================
#define    MDNS_ADDR_T_VERSION                    (MDNS_BASE + 0x0000)
#define    MDNS_ADDR_REG_CTRL                     (MDNS_BASE + 0x0004)
#define    MDNS_ADDR_DBG_SEL                      (MDNS_BASE + 0x0008)
#define    MDNS_ADDR_DBG_VALUE                    (MDNS_BASE + 0x000C)
#define    MDNS_ADDR_Y_REF_BASE_ADDR              (MDNS_BASE + 0x0010)
#define    MDNS_ADDR_Y_REF_STRIDE                 (MDNS_BASE + 0x0014)
#define    MDNS_ADDR_Y_REF_FRM_SIZE               (MDNS_BASE + 0x0018)
#define    MDNS_ADDR_Y_REF_FRM_NUM                (MDNS_BASE + 0x001C)
#define    MDNS_ADDR_UV_REF_BASE_ADDR             (MDNS_BASE + 0x0020)
#define    MDNS_ADDR_UV_REF_STRIDE                (MDNS_BASE + 0x0024)
#define    MDNS_ADDR_UV_REF_FRM_SIZE              (MDNS_BASE + 0x0028)
#define    MDNS_ADDR_UV_REF_FRM_NUM               (MDNS_BASE + 0x002C)
#define    MDNS_ADDR_STA_BASE_ADDR                (MDNS_BASE + 0x0030)
#define    MDNS_ADDR_STA_STRIDE                   (MDNS_BASE + 0x0034)
#define    MDNS_ADDR_STA_FRM_SIZE                 (MDNS_BASE + 0x0038)
#define    MDNS_ADDR_STA_FRM_NUM                  (MDNS_BASE + 0x003C)
#define    MDNS_ADDR_PBT_BASE_ADDR                (MDNS_BASE + 0x0040)
#define    MDNS_ADDR_PBT_STRIDE                   (MDNS_BASE + 0x0044)
#define    MDNS_ADDR_PBT_FRM_SIZE                 (MDNS_BASE + 0x0048)
#define    MDNS_ADDR_PBT_FRM_NUM                  (MDNS_BASE + 0x004C)
#define    MDNS_ADDR_T_FRM_NUM                    (MDNS_BASE + 0x0050)
#define    MDNS_ADDR_T_TOP_FUN                    (MDNS_BASE + 0x0060)
#define    MDNS_ADDR_STA_OVER_CFG                 (MDNS_BASE + 0x0070)
#define    MDNS_ADDR_STA_WIN_CFG                  (MDNS_BASE + 0x0074)
#define    MDNS_ADDR_STA_BLK_SIZE                 (MDNS_BASE + 0x0078)
#define    MDNS_ADDR_STA_BLK_NUM                  (MDNS_BASE + 0x007C)
#define    MDNS_ADDR_STA_MAX_NUM                  (MDNS_BASE + 0x0080)
#define    MDNS_ADDR_STA_DIFF_THRES               (MDNS_BASE + 0x0084)
#define    MDNS_ADDR_STA_MV_NUM_THRES00           (MDNS_BASE + 0x0090)
#define    MDNS_ADDR_STA_MV_NUM_THRES01           (MDNS_BASE + 0x0094)
#define    MDNS_ADDR_STA_MV_NUM_THRES10           (MDNS_BASE + 0x0098)
#define    MDNS_ADDR_STA_MV_NUM_THRES11           (MDNS_BASE + 0x009C)
#define    MDNS_ADDR_PBT_START_POINT              (MDNS_BASE + 0x00A0)
#define    MDNS_ADDR_PBT_WIN_SIZE                 (MDNS_BASE + 0x00A4)
#define    MDNS_ADDR_PBT_OVER_CFG                 (MDNS_BASE + 0x00B0)
#define    MDNS_ADDR_PBT_WIN_CFG                  (MDNS_BASE + 0x00B4)
#define    MDNS_ADDR_PBT_BLK_SIZE                 (MDNS_BASE + 0x00B8)
#define    MDNS_ADDR_PBT_BLK_NUM                  (MDNS_BASE + 0x00BC)
#define    MDNS_ADDR_PBT_MAX_NUM                  (MDNS_BASE + 0x00C0)
#define    MDNS_ADDR_PBT_DIFF_THRES               (MDNS_BASE + 0x00C4)
#define    MDNS_ADDR_PBT_MV_NUM_THRES00           (MDNS_BASE + 0x00D0)
#define    MDNS_ADDR_PBT_MV_NUM_THRES01           (MDNS_BASE + 0x00D4)
#define    MDNS_ADDR_PBT_MV_NUM_THRES10           (MDNS_BASE + 0x00D8)
#define    MDNS_ADDR_PBT_MV_NUM_THRES11           (MDNS_BASE + 0x00DC)
#define    MDNS_ADDR_Y_CUT_VALUE                  (MDNS_BASE + 0x00E0)
#define    MDNS_ADDR_Y_EDGE_PAR                   (MDNS_BASE + 0x00E4)
#define    MDNS_ADDR_Y_BI_PAR0                    (MDNS_BASE + 0x00E8)
#define    MDNS_ADDR_Y_BI_PAR1                    (MDNS_BASE + 0x00EC)
#define    MDNS_ADDR_Y_TCA_PAR                    (MDNS_BASE + 0x00F0)
#define    MDNS_ADDR_Y_TEA_T_PAR0                 (MDNS_BASE + 0x00F4)
#define    MDNS_ADDR_Y_TEA_T_PAR1                 (MDNS_BASE + 0x00F8)
#define    MDNS_ADDR_Y_TEA_V_PAR0                 (MDNS_BASE + 0x00FC)
#define    MDNS_ADDR_Y_TEA_V_PAR1                 (MDNS_BASE + 0x0100)
#define    MDNS_ADDR_Y_TEA_W_PAR0                 (MDNS_BASE + 0x0104)
#define    MDNS_ADDR_Y_TEA_W_PAR1                 (MDNS_BASE + 0x0108)
#define    MDNS_ADDR_Y_TLA_WIN_OPT                (MDNS_BASE + 0x010C)
#define    MDNS_ADDR_Y_TLA_T_PAR0                 (MDNS_BASE + 0x0110)
#define    MDNS_ADDR_Y_TLA_T_PAR1                 (MDNS_BASE + 0x0114)
#define    MDNS_ADDR_Y_TLA_T_PAR2                 (MDNS_BASE + 0x0118)
#define    MDNS_ADDR_Y_TLA_T_PAR3                 (MDNS_BASE + 0x011C)
#define    MDNS_ADDR_Y_TLA_V_PAR0                 (MDNS_BASE + 0x0120)
#define    MDNS_ADDR_Y_TLA_V_PAR1                 (MDNS_BASE + 0x0124)
#define    MDNS_ADDR_Y_TLA_V_PAR2                 (MDNS_BASE + 0x0128)
#define    MDNS_ADDR_Y_TLA_V_PAR3                 (MDNS_BASE + 0x012C)
#define    MDNS_ADDR_Y_TLA_W_PAR0                 (MDNS_BASE + 0x0130)
#define    MDNS_ADDR_Y_TLA_W_PAR1                 (MDNS_BASE + 0x0134)
#define    MDNS_ADDR_Y_TLA_W_PAR2                 (MDNS_BASE + 0x0138)
#define    MDNS_ADDR_Y_TLA_W_PAR3                 (MDNS_BASE + 0x013C)
#define    MDNS_ADDR_Y_SAD_CFG                    (MDNS_BASE + 0x0140)
#define    MDNS_ADDR_Y_STA_WEI_PAR0               (MDNS_BASE + 0x0150)
#define    MDNS_ADDR_Y_STA_WEI_PAR1               (MDNS_BASE + 0x0154)
#define    MDNS_ADDR_Y_STA_WEI_PAR2               (MDNS_BASE + 0x0158)
#define    MDNS_ADDR_Y_STA_WEI_PAR3               (MDNS_BASE + 0x015C)
#define    MDNS_ADDR_Y_STA_WEI_PAR4               (MDNS_BASE + 0x0160)
#define    MDNS_ADDR_Y_STA_WEI_PAR5               (MDNS_BASE + 0x0164)
#define    MDNS_ADDR_Y_STA_WEI_PAR6               (MDNS_BASE + 0x0168)
#define    MDNS_ADDR_Y_STA_WEI_PAR7               (MDNS_BASE + 0x016C)
#define    MDNS_ADDR_Y_STA_WEI_PAR8               (MDNS_BASE + 0x0170)
#define    MDNS_ADDR_Y_STA_WEI_PAR9               (MDNS_BASE + 0x0174)
#define    MDNS_ADDR_Y_STA_WEI_PARa               (MDNS_BASE + 0x0178)
#define    MDNS_ADDR_Y_STA_WEI_PARb               (MDNS_BASE + 0x017C)
#define    MDNS_ADDR_Y_STA_WEI_PARc               (MDNS_BASE + 0x0180)
#define    MDNS_ADDR_Y_STA_WEI_PARd               (MDNS_BASE + 0x0184)
#define    MDNS_ADDR_Y_STA_WEI_PARe               (MDNS_BASE + 0x0188)
#define    MDNS_ADDR_Y_STA_WEI_PARf               (MDNS_BASE + 0x018C)
#define    MDNS_ADDR_Y_PBT_WEI_PAR0               (MDNS_BASE + 0x0190)
#define    MDNS_ADDR_Y_PBT_WEI_PAR1               (MDNS_BASE + 0x0194)
#define    MDNS_ADDR_Y_PBT_WEI_PAR2               (MDNS_BASE + 0x0198)
#define    MDNS_ADDR_Y_PBT_WEI_PAR3               (MDNS_BASE + 0x019C)
#define    MDNS_ADDR_Y_PBT_WEI_PAR4               (MDNS_BASE + 0x01A0)
#define    MDNS_ADDR_Y_PBT_WEI_PAR5               (MDNS_BASE + 0x01A4)
#define    MDNS_ADDR_Y_PBT_WEI_PAR6               (MDNS_BASE + 0x01A8)
#define    MDNS_ADDR_Y_PBT_WEI_PAR7               (MDNS_BASE + 0x01AC)
#define    MDNS_ADDR_Y_PBT_WEI_PAR8               (MDNS_BASE + 0x01B0)
#define    MDNS_ADDR_Y_PBT_WEI_PAR9               (MDNS_BASE + 0x01B4)
#define    MDNS_ADDR_Y_PBT_WEI_PARa               (MDNS_BASE + 0x01B8)
#define    MDNS_ADDR_Y_PBT_WEI_PARb               (MDNS_BASE + 0x01BC)
#define    MDNS_ADDR_Y_PBT_WEI_PARc               (MDNS_BASE + 0x01C0)
#define    MDNS_ADDR_Y_PBT_WEI_PARd               (MDNS_BASE + 0x01C4)
#define    MDNS_ADDR_Y_PBT_WEI_PARe               (MDNS_BASE + 0x01C8)
#define    MDNS_ADDR_Y_PBT_WEI_PARf               (MDNS_BASE + 0x01CC)
#define    MDNS_ADDR_Y_WSA_S_PAR                  (MDNS_BASE + 0x01D0)
#define    MDNS_ADDR_Y_WSA_M_PAR                  (MDNS_BASE + 0x01D4)
#define    MDNS_ADDR_Y_WFA_PAR                    (MDNS_BASE + 0x01D8)
#define    MDNS_ADDR_Y_REF_WEI_LMT                (MDNS_BASE + 0x01DC)
#define    MDNS_ADDR_Y_REF_WEI_SGM_X_PAR0         (MDNS_BASE + 0x01E0)
#define    MDNS_ADDR_Y_REF_WEI_SGM_X_PAR1         (MDNS_BASE + 0x01E4)
#define    MDNS_ADDR_Y_REF_WEI_SGM_X_PAR2         (MDNS_BASE + 0x01E8)
#define    MDNS_ADDR_Y_REF_WEI_SGM_Y_PAR0         (MDNS_BASE + 0x01EC)
#define    MDNS_ADDR_Y_REF_WEI_SGM_Y_PAR1         (MDNS_BASE + 0x01F0)
#define    MDNS_ADDR_Y_REF_WEI_SGM_S_PAR0         (MDNS_BASE + 0x01F4)
#define    MDNS_ADDR_Y_REF_WEI_SGM_S_PAR1         (MDNS_BASE + 0x01F8)
#define    MDNS_ADDR_Y_FS_MV_JUDGE_THRES          (MDNS_BASE + 0x01FC)
#define    MDNS_ADDR_Y_FS_S_CUR_SHP_WIN_OPT       (MDNS_BASE + 0x0200)
#define    MDNS_ADDR_Y_FS_S_CUR_SHP_STREN_P0      (MDNS_BASE + 0x0204)
#define    MDNS_ADDR_Y_FS_S_CUR_SHP_STREN_P1      (MDNS_BASE + 0x0208)
#define    MDNS_ADDR_Y_FS_S_CUR_SHP_STREN_P2      (MDNS_BASE + 0x020C)
#define    MDNS_ADDR_Y_FS_S_CUR_SHP_STREN_P3      (MDNS_BASE + 0x0210)
#define    MDNS_ADDR_Y_FS_S_REF_SHP_WIN_OPT       (MDNS_BASE + 0x0214)
#define    MDNS_ADDR_Y_FS_S_REF_SHP_STREN_P0      (MDNS_BASE + 0x0218)
#define    MDNS_ADDR_Y_FS_S_REF_SHP_STREN_P1      (MDNS_BASE + 0x021C)
#define    MDNS_ADDR_Y_FS_S_REF_SHP_STREN_P2      (MDNS_BASE + 0x0220)
#define    MDNS_ADDR_Y_FS_S_REF_SHP_STREN_P3      (MDNS_BASE + 0x0224)
#define    MDNS_ADDR_Y_FS_S_SHP_WEI               (MDNS_BASE + 0x0228)
#define    MDNS_ADDR_Y_FS_M_CUR_SHP_WIN_OPT       (MDNS_BASE + 0x022C)
#define    MDNS_ADDR_Y_FS_M_CUR_SHP_STREN_P0      (MDNS_BASE + 0x0230)
#define    MDNS_ADDR_Y_FS_M_CUR_SHP_STREN_P1      (MDNS_BASE + 0x0234)
#define    MDNS_ADDR_Y_FS_M_CUR_SHP_STREN_P2      (MDNS_BASE + 0x0238)
#define    MDNS_ADDR_Y_FS_M_CUR_SHP_STREN_P3      (MDNS_BASE + 0x023C)
#define    MDNS_ADDR_Y_FS_M_REF_SHP_WIN_OPT       (MDNS_BASE + 0x0240)
#define    MDNS_ADDR_Y_FS_M_REF_SHP_STREN_P0      (MDNS_BASE + 0x0244)
#define    MDNS_ADDR_Y_FS_M_REF_SHP_STREN_P1      (MDNS_BASE + 0x0248)
#define    MDNS_ADDR_Y_FS_M_REF_SHP_STREN_P2      (MDNS_BASE + 0x024C)
#define    MDNS_ADDR_Y_FS_M_REF_SHP_STREN_P3      (MDNS_BASE + 0x0250)
#define    MDNS_ADDR_Y_FS_M_SHP_WEI               (MDNS_BASE + 0x0254)
#define    MDNS_ADDR_Y_FS_SHP_CUR_STA_WEI_P0      (MDNS_BASE + 0x0258)
#define    MDNS_ADDR_Y_FS_SHP_CUR_STA_WEI_P1      (MDNS_BASE + 0x025C)
#define    MDNS_ADDR_Y_FS_SHP_REF_STA_WEI_P0      (MDNS_BASE + 0x0260)
#define    MDNS_ADDR_Y_FS_SHP_REF_STA_WEI_P1      (MDNS_BASE + 0x0264)
#define    MDNS_ADDR_Y_FS_SHP_CUR_FLUCT_PAR       (MDNS_BASE + 0x0268)
#define    MDNS_ADDR_Y_FS_SHP_REF_FLUCT_PAR       (MDNS_BASE + 0x026C)
#define    MDNS_ADDR_UV_CUT_VALUE                 (MDNS_BASE + 0x0280)
#define    MDNS_ADDR_UV_SAD_CFG                   (MDNS_BASE + 0x0284)
#define    MDNS_ADDR_UV_TCA_PAR                   (MDNS_BASE + 0x0290)
#define    MDNS_ADDR_UV_TMA_T_PAR0                (MDNS_BASE + 0x0294)
#define    MDNS_ADDR_UV_TMA_T_PAR1                (MDNS_BASE + 0x0298)
#define    MDNS_ADDR_UV_TMA_V_PAR0                (MDNS_BASE + 0x029C)
#define    MDNS_ADDR_UV_TMA_V_PAR1                (MDNS_BASE + 0x02a0)
#define    MDNS_ADDR_UV_TMA_W_PAR0                (MDNS_BASE + 0x02a4)
#define    MDNS_ADDR_UV_TMA_W_PAR1                (MDNS_BASE + 0x02a8)
#define    MDNS_ADDR_UV_STA_WEI_PAR0              (MDNS_BASE + 0x02b0)
#define    MDNS_ADDR_UV_STA_WEI_PAR1              (MDNS_BASE + 0x02b4)
#define    MDNS_ADDR_UV_STA_WEI_PAR2              (MDNS_BASE + 0x02b8)
#define    MDNS_ADDR_UV_STA_WEI_PAR3              (MDNS_BASE + 0x02bC)
#define    MDNS_ADDR_UV_STA_WEI_PAR4              (MDNS_BASE + 0x02c0)
#define    MDNS_ADDR_UV_STA_WEI_PAR5              (MDNS_BASE + 0x02c4)
#define    MDNS_ADDR_UV_STA_WEI_PAR6              (MDNS_BASE + 0x02c8)
#define    MDNS_ADDR_UV_STA_WEI_PAR7              (MDNS_BASE + 0x02cC)
#define    MDNS_ADDR_UV_STA_WEI_PAR8              (MDNS_BASE + 0x02d0)
#define    MDNS_ADDR_UV_STA_WEI_PAR9              (MDNS_BASE + 0x02d4)
#define    MDNS_ADDR_UV_STA_WEI_PARa              (MDNS_BASE + 0x02d8)
#define    MDNS_ADDR_UV_STA_WEI_PARb              (MDNS_BASE + 0x02dC)
#define    MDNS_ADDR_UV_STA_WEI_PARc              (MDNS_BASE + 0x02e0)
#define    MDNS_ADDR_UV_STA_WEI_PARd              (MDNS_BASE + 0x02e4)
#define    MDNS_ADDR_UV_STA_WEI_PARe              (MDNS_BASE + 0x02e8)
#define    MDNS_ADDR_UV_STA_WEI_PARf              (MDNS_BASE + 0x02eC)
#define    MDNS_ADDR_UV_PBT_WEI_PAR0              (MDNS_BASE + 0x02f0)
#define    MDNS_ADDR_UV_PBT_WEI_PAR1              (MDNS_BASE + 0x02f4)
#define    MDNS_ADDR_UV_PBT_WEI_PAR2              (MDNS_BASE + 0x02f8)
#define    MDNS_ADDR_UV_PBT_WEI_PAR3              (MDNS_BASE + 0x02fC)
#define    MDNS_ADDR_UV_PBT_WEI_PAR4              (MDNS_BASE + 0x0300)
#define    MDNS_ADDR_UV_PBT_WEI_PAR5              (MDNS_BASE + 0x0304)
#define    MDNS_ADDR_UV_PBT_WEI_PAR6              (MDNS_BASE + 0x0308)
#define    MDNS_ADDR_UV_PBT_WEI_PAR7              (MDNS_BASE + 0x030C)
#define    MDNS_ADDR_UV_PBT_WEI_PAR8              (MDNS_BASE + 0x0310)
#define    MDNS_ADDR_UV_PBT_WEI_PAR9              (MDNS_BASE + 0x0314)
#define    MDNS_ADDR_UV_PBT_WEI_PARa              (MDNS_BASE + 0x0318)
#define    MDNS_ADDR_UV_PBT_WEI_PARb              (MDNS_BASE + 0x031C)
#define    MDNS_ADDR_UV_PBT_WEI_PARc              (MDNS_BASE + 0x0320)
#define    MDNS_ADDR_UV_PBT_WEI_PARd              (MDNS_BASE + 0x0324)
#define    MDNS_ADDR_UV_PBT_WEI_PARe              (MDNS_BASE + 0x0328)
#define    MDNS_ADDR_UV_PBT_WEI_PARf              (MDNS_BASE + 0x032C)
#define    MDNS_ADDR_UV_WSA_S_PAR                 (MDNS_BASE + 0x0330)
#define    MDNS_ADDR_UV_WSA_M_PAR                 (MDNS_BASE + 0x0334)
#define    MDNS_ADDR_UV_REF_WEI_LMT               (MDNS_BASE + 0x0338)
#define    MDNS_ADDR_UV_REF_WEI_SGM_X_PAR0        (MDNS_BASE + 0x0340)
#define    MDNS_ADDR_UV_REF_WEI_SGM_X_PAR1        (MDNS_BASE + 0x0344)
#define    MDNS_ADDR_UV_REF_WEI_SGM_X_PAR2        (MDNS_BASE + 0x0348)
#define    MDNS_ADDR_UV_REF_WEI_SGM_Y_PAR0        (MDNS_BASE + 0x034C)
#define    MDNS_ADDR_UV_REF_WEI_SGM_Y_PAR1        (MDNS_BASE + 0x0350)
#define    MDNS_ADDR_UV_REF_WEI_SGM_S_PAR0        (MDNS_BASE + 0x0354)
#define    MDNS_ADDR_UV_REF_WEI_SGM_S_PAR1        (MDNS_BASE + 0x0358)
#define    MDNS_ADDR_UV_FS_MV_JUDGE_THRES         (MDNS_BASE + 0x035C)
#define    MDNS_ADDR_UV_FC_TYPE                   (MDNS_BASE + 0x0360)
#define    MDNS_ADDR_UV_FC_S_PAR0                 (MDNS_BASE + 0x0370)
#define    MDNS_ADDR_UV_FC_S_PAR1                 (MDNS_BASE + 0x0374)
#define    MDNS_ADDR_UV_FC_M_PAR0                 (MDNS_BASE + 0x0378)
#define    MDNS_ADDR_UV_FC_M_PAR1                 (MDNS_BASE + 0x037C)
#define    MDNS_ADDR_UV_BLUR_WEI                  (MDNS_BASE + 0x0380)

//============================================================
// SDNS
//============================================================
#define    SDNS_ADDR_T_VERSION                    (SDNS_BASE + 0x0000)
#define    SDNS_ADDR_REG_CTRL                     (SDNS_BASE + 0x0004)
#define    SDNS_ADDR_DBG_SEL                      (SDNS_BASE + 0x0008)
#define    SDNS_ADDR_DBG_VALUE                    (SDNS_BASE + 0x000C)
#define    SDNS_ADDR_Y_FUN_EN                     (SDNS_BASE + 0x0010)
#define    SDNS_ADDR_Y_COM_PAR0                   (SDNS_BASE + 0x0014)
#define    SDNS_ADDR_Y_COM_PAR1                   (SDNS_BASE + 0x0018)
#define    SDNS_ADDR_Y_FUSION_PAR0                (SDNS_BASE + 0x001C)
#define    SDNS_ADDR_Y_FUSION_PAR1                (SDNS_BASE + 0x0020)
#define    SDNS_ADDR_Y_FUSION_PAR2                (SDNS_BASE + 0x0024)
#define    SDNS_ADDR_Y_FUSION_PAR3                (SDNS_BASE + 0x0028)
#define    SDNS_ADDR_Y_DETAIL_PAR0                (SDNS_BASE + 0x002C)
#define    SDNS_ADDR_Y_DETAIL_PAR1                (SDNS_BASE + 0x0030)
#define    SDNS_ADDR_Y_DETAIL_PAR2                (SDNS_BASE + 0x0034)
#define    SDNS_ADDR_Y_DETAIL_PAR3                (SDNS_BASE + 0x0038)
#define    SDNS_ADDR_Y_LUMA_PAR0                  (SDNS_BASE + 0x003C)
#define    SDNS_ADDR_Y_LUMA_PAR1                  (SDNS_BASE + 0x0040)
#define    SDNS_ADDR_Y_LUMA_PAR2                  (SDNS_BASE + 0x0044)
#define    SDNS_ADDR_Y_LUMA_PAR3                  (SDNS_BASE + 0x0048)
#define    SDNS_ADDR_Y_BSHP_PAR0                  (SDNS_BASE + 0x004C)
#define    SDNS_ADDR_Y_BSHP_PAR1                  (SDNS_BASE + 0x0050)
#define    SDNS_ADDR_Y_BSHP_PAR2                  (SDNS_BASE + 0x0054)
#define    SDNS_ADDR_Y_BSHP_PAR3                  (SDNS_BASE + 0x0058)
#define    SDNS_ADDR_Y_DSHP_PAR0                  (SDNS_BASE + 0x005C)
#define    SDNS_ADDR_Y_DSHP_PAR1                  (SDNS_BASE + 0x0060)
#define    SDNS_ADDR_Y_DSHP_PAR2                  (SDNS_BASE + 0x0064)
#define    SDNS_ADDR_Y_DSHP_PAR3                  (SDNS_BASE + 0x0068)
#define    SDNS_ADDR_Y_BI_PAR0                    (SDNS_BASE + 0x006C)
#define    SDNS_ADDR_Y_BI_PAR1                    (SDNS_BASE + 0x0070)
#define    SDNS_ADDR_Y_BI_PAR2                    (SDNS_BASE + 0x0074)
#define    SDNS_ADDR_Y_BI_PAR3                    (SDNS_BASE + 0x0078)
#define    SDNS_ADDR_UV_FUN_EN                    (SDNS_BASE + 0x0080)
#define    SDNS_ADDR_UV_COM_PAR                   (SDNS_BASE + 0x0084)
#define    SDNS_ADDR_UV_FUSION_PAR0               (SDNS_BASE + 0x0088)
#define    SDNS_ADDR_UV_FUSION_PAR1               (SDNS_BASE + 0x008C)
#define    SDNS_ADDR_UV_FUSION_PAR2               (SDNS_BASE + 0x0090)
#define    SDNS_ADDR_UV_FUSION_PAR3               (SDNS_BASE + 0x0094)

//============================================================
// HLDC
//============================================================
#define    HLDC_ADDR_REG_CTRL                     (HLDC_BASE + 0x0000)
#define    HLDC_ADDR_DIS_Y_COEFF_X                (HLDC_BASE + 0x0004)
#define    HLDC_ADDR_DIS_UV_COEFF_X               (HLDC_BASE + 0x0008)
#define    HLDC_ADDR_P1_Y_VAL                     (HLDC_BASE + 0x000C)
#define    HLDC_ADDR_P1_UV_VAL                    (HLDC_BASE + 0x0010)
#define    HLDC_ADDR_R2_Y_REP                     (HLDC_BASE + 0x0014)
#define    HLDC_ADDR_R2_UV_REP                    (HLDC_BASE + 0x0018)
#define    HLDC_ADDR_Y_OFFSET                     (HLDC_BASE + 0x001C)
#define    HLDC_ADDR_UV_OFFSET                    (HLDC_BASE + 0x0020)
#define    HLDC_ADDR_LINE_BLK_Y                   (HLDC_BASE + 0x0024)
#define    HLDC_ADDR_LINE_BLK_UV                  (HLDC_BASE + 0x0028)

//============================================================
// Mscaler
//============================================================
#define    MSCA_CTRL                         (MSCA_BASE+0x000)
#define    MSCA_CH_EN                        (MSCA_BASE+0x004)
#define    MSCA_CH_STA                       (MSCA_BASE+0x008)
#define    MSCA_INT_STA                      (MSCA_BASE+0x00C)
#define    MSCA_INT_MSK                      (MSCA_BASE+0x010)
#define    MSCA_INT_CLR                      (MSCA_BASE+0x014)
#define    MSCA_DMAOUT_ARB                   (MSCA_BASE+0x018)
#define    MSCA_CLK_GATE_EN                  (MSCA_BASE+0x01C)
#define    MSCA_CLK_DIS                      (MSCA_BASE+0x020)
#define    MSCA_SRC_IN                       (MSCA_BASE+0x030)
#define    MSCA_SRC_SIZE                     (MSCA_BASE+0x034)
#define    MSCA_GLO_RSZ_COEF_WR              (MSCA_BASE+0x040)
#define    MSCA_SYS_PRO_CLK_EN               (MSCA_BASE+0x050)
#define    MSCA_DS0_CLK_NUM                  (MSCA_BASE+0x054)
#define    MSCA_DS1_CLK_NUM                  (MSCA_BASE+0x058)
#define    MSCA_DS2_CLK_NUM                  (MSCA_BASE+0x05C)

//ds0
#define    MSCA_ADDR_DS0_RSZ_SIZE                 (MSCA_BASE+0x100)
#define    MSCA_ADDR_DS0_RSZ_STEP                 (MSCA_BASE+0x104)
#define    MSCA_ADDR_DS0_CROP_POS                 (MSCA_BASE+0x128)
#define    MSCA_ADDR_DS0_CROP_SIZE                (MSCA_BASE+0x12C)
#define    MSCA_ADDR_DS0_FRA_RATE_LOOP            (MSCA_BASE+0x130)
#define    MSCA_ADDR_DS0_FRA_RATE_MASK            (MSCA_BASE+0x134)
#define    MSCA_ADDR_DS0_MASK0_POS                (MSCA_BASE+0x138)
#define    MSCA_ADDR_DS0_MASK0_SIZE               (MSCA_BASE+0x13C)
#define    MSCA_ADDR_DS0_MASK0_ARGB               (MSCA_BASE+0x140)
#define    MSCA_ADDR_DS0_MASK1_POS                (MSCA_BASE+0x144)
#define    MSCA_ADDR_DS0_MASK1_SIZE               (MSCA_BASE+0x148)
#define    MSCA_ADDR_DS0_MASK1_ARGB               (MSCA_BASE+0x14C)
#define    MSCA_ADDR_DS0_MASK2_POS                (MSCA_BASE+0x150)
#define    MSCA_ADDR_DS0_MASK2_SIZE               (MSCA_BASE+0x154)
#define    MSCA_ADDR_DS0_MASK2_ARGB               (MSCA_BASE+0x158)
#define    MSCA_ADDR_DS0_MASK3_POS                (MSCA_BASE+0x15C)
#define    MSCA_ADDR_DS0_MASK3_SIZE               (MSCA_BASE+0x160)
#define    MSCA_ADDR_DS0_MASK3_ARGB               (MSCA_BASE+0x164)
#define    MSCA_ADDR_DS0_DMAOUT_FMT               (MSCA_BASE+0x168)
#define    MSCA_ADDR_DS0_DMAOUT_Y_ADDR            (MSCA_BASE+0x16C)
#define    MSCA_ADDR_DS0_DMAOUT_Y_FIFO_STA        (MSCA_BASE+0x170)
#define    MSCA_ADDR_DS0_DMAOUT_Y_LAST_ADDR       (MSCA_BASE+0x174)
#define    MSCA_ADDR_DS0_DMAOUT_Y_LAST_STATS_NUM  (MSCA_BASE+0x178)
#define    MSCA_ADDR_DS0_DMAOUT_Y_LAST_FIFO_STA   (MSCA_BASE+0x17C)
#define    MSCA_ADDR_DS0_DMAOUT_Y_STR             (MSCA_BASE+0x180)
#define    MSCA_ADDR_DS0_DMAOUT_UV_ADDR           (MSCA_BASE+0x184)
#define    MSCA_ADDR_DS0_DMAOUT_UV_FIFO_STA       (MSCA_BASE+0x188)
#define    MSCA_ADDR_DS0_DMAOUT_UV_LAST_ADDR      (MSCA_BASE+0x18C)
#define    MSCA_ADDR_DS0_DMAOUT_UV_LAST_STATS_NUM (MSCA_BASE+0x190)
#define    MSCA_ADDR_DS0_DMAOUT_UV_LAST_FIFO_STA  (MSCA_BASE+0x194)
#define    MSCA_ADDR_DS0_DMAOUT_UV_STR            (MSCA_BASE+0x198)
#define    MSCA_ADDR_DS0_DMAOUT_Y_FIFO_CLR        (MSCA_BASE+0x19C)
#define    MSCA_ADDR_DS0_DMAOUT_UV_FIFO_CLR       (MSCA_BASE+0x1A0)
#define    MSCA_ADDR_DS0_DMAOUT_Y_LAST_FIFO_CLR   (MSCA_BASE+0x1A4)
#define    MSCA_ADDR_DS0_DMAOUT_UV_LAST_FIFO_CLR  (MSCA_BASE+0x1A8)
#define    MSCA_ADDR_DS0_DMAOUT_Y_ADDR_SEL        (MSCA_BASE+0x1AC)
#define    MSCA_ADDR_DS0_DMAOUT_UV_ADDR_SEL       (MSCA_BASE+0x1B0)

//-- ds1
#define    MSCA_ADDR_DS1_RSZ_SIZE                 (MSCA_BASE+0x200)
#define    MSCA_ADDR_DS1_RSZ_STEP                 (MSCA_BASE+0x204)
#define    MSCA_ADDR_DS1_CROP_POS                 (MSCA_BASE+0x228)
#define    MSCA_ADDR_DS1_CROP_SIZE                (MSCA_BASE+0x22C)
#define    MSCA_ADDR_DS1_FRA_RATE_LOOP            (MSCA_BASE+0x230)
#define    MSCA_ADDR_DS1_FRA_RATE_MASK            (MSCA_BASE+0x234)
#define    MSCA_ADDR_DS1_MASK0_POS                (MSCA_BASE+0x238)
#define    MSCA_ADDR_DS1_MASK0_SIZE               (MSCA_BASE+0x23C)
#define    MSCA_ADDR_DS1_MASK0_ARGB               (MSCA_BASE+0x240)
#define    MSCA_ADDR_DS1_MASK1_POS                (MSCA_BASE+0x244)
#define    MSCA_ADDR_DS1_MASK1_SIZE               (MSCA_BASE+0x248)
#define    MSCA_ADDR_DS1_MASK1_ARGB               (MSCA_BASE+0x24C)
#define    MSCA_ADDR_DS1_MASK2_POS                (MSCA_BASE+0x250)
#define    MSCA_ADDR_DS1_MASK2_SIZE               (MSCA_BASE+0x254)
#define    MSCA_ADDR_DS1_MASK2_ARGB               (MSCA_BASE+0x258)
#define    MSCA_ADDR_DS1_MASK3_POS                (MSCA_BASE+0x25C)
#define    MSCA_ADDR_DS1_MASK3_SIZE               (MSCA_BASE+0x260)
#define    MSCA_ADDR_DS1_MASK3_ARGB               (MSCA_BASE+0x264)
#define    MSCA_ADDR_DS1_DMAOUT_FMT               (MSCA_BASE+0x268)
#define    MSCA_ADDR_DS1_DMAOUT_Y_ADDR            (MSCA_BASE+0x26C)
#define    MSCA_ADDR_DS1_DMAOUT_Y_FIFO_STA        (MSCA_BASE+0x270)
#define    MSCA_ADDR_DS1_DMAOUT_Y_LAST_ADDR       (MSCA_BASE+0x274)
#define    MSCA_ADDR_DS1_DMAOUT_Y_LAST_STATS_NUM  (MSCA_BASE+0x278)
#define    MSCA_ADDR_DS1_DMAOUT_Y_LAST_FIFO_STA   (MSCA_BASE+0x27C)
#define    MSCA_ADDR_DS1_DMAOUT_Y_STR             (MSCA_BASE+0x280)
#define    MSCA_ADDR_DS1_DMAOUT_UV_ADDR           (MSCA_BASE+0x284)
#define    MSCA_ADDR_DS1_DMAOUT_UV_FIFO_STA       (MSCA_BASE+0x288)
#define    MSCA_ADDR_DS1_DMAOUT_UV_LAST_ADDR      (MSCA_BASE+0x28C)
#define    MSCA_ADDR_DS1_DMAOUT_UV_LAST_STATS_NUM (MSCA_BASE+0x290)
#define    MSCA_ADDR_DS1_DMAOUT_UV_LAST_FIFO_STA  (MSCA_BASE+0x294)
#define    MSCA_ADDR_DS1_DMAOUT_UV_STR            (MSCA_BASE+0x298)
#define    MSCA_ADDR_DS1_DMAOUT_Y_FIFO_CLR        (MSCA_BASE+0x29C)
#define    MSCA_ADDR_DS1_DMAOUT_UV_FIFO_CLR       (MSCA_BASE+0x2A0)
#define    MSCA_ADDR_DS1_DMAOUT_Y_LAST_FIFO_CLR   (MSCA_BASE+0x2A4)
#define    MSCA_ADDR_DS1_DMAOUT_UV_LAST_FIFO_CLR  (MSCA_BASE+0x2A8)
#define    MSCA_ADDR_DS1_DMAOUT_Y_ADDR_SEL        (MSCA_BASE+0x2AC)
#define    MSCA_ADDR_DS1_DMAOUT_UV_ADDR_SEL       (MSCA_BASE+0x2B0)


//-- ds2
#define    MSCA_ADDR_DS2_RSZ_SIZE                 (MSCA_BASE+0x300)
#define    MSCA_ADDR_DS2_RSZ_STEP                 (MSCA_BASE+0x304)
#define    MSCA_ADDR_DS2_CROP_POS                 (MSCA_BASE+0x328)
#define    MSCA_ADDR_DS2_CROP_SIZE                (MSCA_BASE+0x32C)
#define    MSCA_ADDR_DS2_FRA_RATE_LOOP            (MSCA_BASE+0x330)
#define    MSCA_ADDR_DS2_FRA_RATE_MASK            (MSCA_BASE+0x334)
#define    MSCA_ADDR_DS2_MASK0_POS                (MSCA_BASE+0x338)
#define    MSCA_ADDR_DS2_MASK0_SIZE               (MSCA_BASE+0x33C)
#define    MSCA_ADDR_DS2_MASK0_ARGB               (MSCA_BASE+0x340)
#define    MSCA_ADDR_DS2_MASK1_POS                (MSCA_BASE+0x344)
#define    MSCA_ADDR_DS2_MASK1_SIZE               (MSCA_BASE+0x348)
#define    MSCA_ADDR_DS2_MASK1_ARGB               (MSCA_BASE+0x34C)
#define    MSCA_ADDR_DS2_MASK2_POS                (MSCA_BASE+0x350)
#define    MSCA_ADDR_DS2_MASK2_SIZE               (MSCA_BASE+0x354)
#define    MSCA_ADDR_DS2_MASK2_ARGB               (MSCA_BASE+0x358)
#define    MSCA_ADDR_DS2_MASK3_POS                (MSCA_BASE+0x35C)
#define    MSCA_ADDR_DS2_MASK3_SIZE               (MSCA_BASE+0x360)
#define    MSCA_ADDR_DS2_MASK3_ARGB               (MSCA_BASE+0x364)
#define    MSCA_ADDR_DS2_DMAOUT_FMT               (MSCA_BASE+0x368)
#define    MSCA_ADDR_DS2_DMAOUT_Y_ADDR            (MSCA_BASE+0x36C)
#define    MSCA_ADDR_DS2_DMAOUT_Y_FIFO_STA        (MSCA_BASE+0x370)
#define    MSCA_ADDR_DS2_DMAOUT_Y_LAST_ADDR       (MSCA_BASE+0x374)
#define    MSCA_ADDR_DS2_DMAOUT_Y_LAST_STATS_NUM  (MSCA_BASE+0x378)
#define    MSCA_ADDR_DS2_DMAOUT_Y_LAST_FIFO_STA   (MSCA_BASE+0x37C)
#define    MSCA_ADDR_DS2_DMAOUT_Y_STR             (MSCA_BASE+0x380)
#define    MSCA_ADDR_DS2_DMAOUT_UV_ADDR           (MSCA_BASE+0x384)
#define    MSCA_ADDR_DS2_DMAOUT_UV_FIFO_STA       (MSCA_BASE+0x388)
#define    MSCA_ADDR_DS2_DMAOUT_UV_LAST_ADDR      (MSCA_BASE+0x38C)
#define    MSCA_ADDR_DS2_DMAOUT_UV_LAST_STATS_NUM (MSCA_BASE+0x390)
#define    MSCA_ADDR_DS2_DMAOUT_UV_LAST_FIFO_STA  (MSCA_BASE+0x394)
#define    MSCA_ADDR_DS2_DMAOUT_UV_STR            (MSCA_BASE+0x398)
#define    MSCA_ADDR_DS2_DMAOUT_Y_FIFO_CLR        (MSCA_BASE+0x39C)
#define    MSCA_ADDR_DS2_DMAOUT_UV_FIFO_CLR       (MSCA_BASE+0x3A0)
#define    MSCA_ADDR_DS2_DMAOUT_Y_LAST_FIFO_CLR   (MSCA_BASE+0x3A4)
#define    MSCA_ADDR_DS2_DMAOUT_UV_LAST_FIFO_CLR  (MSCA_BASE+0x3A8)
#define    MSCA_ADDR_DS2_DMAOUT_Y_ADDR_SEL        (MSCA_BASE+0x3AC)
#define    MSCA_ADDR_DS2_DMAOUT_UV_ADDR_SEL       (MSCA_BASE+0x3B0)

//--DEBUG
#define    MSCA_ADDR_VRSZ_Y_DBG_SEL               (MSCA_BASE+0x080)
#define    MSCA_ADDR_VRSZ_UV_DBG_SEL              (MSCA_BASE+0x084)
#define    MSCA_ADDR_DS0_DMA_OUT_DBG0_SEL         (MSCA_BASE+0x088)
#define    MSCA_ADDR_DS0_DMA_OUT_DBG1_SEL         (MSCA_BASE+0x08C)
#define    MSCA_ADDR_DS0_DMA_OUT_DBG2_SEL         (MSCA_BASE+0x090)
#define    MSCA_ADDR_DS1_DMA_OUT_DBG0_SEL         (MSCA_BASE+0x094)
#define    MSCA_ADDR_DS1_DMA_OUT_DBG1_SEL         (MSCA_BASE+0x098)
#define    MSCA_ADDR_DS1_DMA_OUT_DBG2_SEL         (MSCA_BASE+0x09C)
#define    MSCA_ADDR_DS2_DMA_OUT_DBG0_SEL         (MSCA_BASE+0x0A0)
#define    MSCA_ADDR_DS2_DMA_OUT_DBG1_SEL         (MSCA_BASE+0x0A4)
#define    MSCA_ADDR_DS2_DMA_OUT_DBG2_SEL         (MSCA_BASE+0x0A8)
#define    MSCA_ADDR_DS0_HRSZ_Y_DBG_SEL           (MSCA_BASE+0x0AC)
#define    MSCA_ADDR_DS0_HRSZ_UV_DBG_SEL          (MSCA_BASE+0x0B0)
#define    MSCA_ADDR_DS1_HRSZ_Y_DBG_SEL           (MSCA_BASE+0x0B4)
#define    MSCA_ADDR_DS1_HRSZ_UV_DBG_SEL          (MSCA_BASE+0x0B8)
#define    MSCA_ADDR_DS2_HRSZ_Y_DBG_SEL           (MSCA_BASE+0x0BC)
#define    MSCA_ADDR_DS2_HRSZ_UV_DBG_SEL          (MSCA_BASE+0x0C0)
#define    MSCA_ADDR_BP_BUS0_DBG_SEL              (MSCA_BASE+0x0C4)
#define    MSCA_ADDR_BP_BUS1_DBG_SEL              (MSCA_BASE+0x0C8)
#define    MSCA_ADDR_BP_BUS2_DBG_SEL              (MSCA_BASE+0x0CC)
#define    MSCA_ADDR_STP_DBG_SEL                  (MSCA_BASE+0x0D0)

#define    MSCA_ADDR_DS0_CRC_Y_SEL                (MSCA_BASE+0x0E0)
#define    MSCA_ADDR_DS0_CRC_UV_SEL               (MSCA_BASE+0x0E4)
#define    MSCA_ADDR_DS1_CRC_Y_SEL                (MSCA_BASE+0x0E8)
#define    MSCA_ADDR_DS1_CRC_UV_SEL               (MSCA_BASE+0x0EC)
#define    MSCA_ADDR_DS2_CRC_Y_SEL                (MSCA_BASE+0x0F0)
#define    MSCA_ADDR_DS2_CRC_UV_SEL               (MSCA_BASE+0x0F4)

#define CHx_RSZ_OSIZE(n)				(MSCA_BASE+(0x0100*(n))+0x100)
#define CHx_RSZ_STEP(n)					(MSCA_BASE+(0x0100*(n))+0x104)

#define CHx_CROP_OPOS(n)				(MSCA_BASE+(0x0100*(n))+0x128)
#define CHx_CROP_OSIZE(n)				(MSCA_BASE+(0x0100*(n))+0x12c)
#define CHx_FRA_CTRL_LOOP(n)				(MSCA_BASE+(0x0100*(n))+0x130)
#define CHx_FRA_CTRL_MASK(n)				(MSCA_BASE+(0x0100*(n))+0x134)
#define CHx_MS0_POS(n)					(MSCA_BASE+(0x0100*(n))+0x138)
#define CHx_MS0_SIZE(n)					(MSCA_BASE+(0x0100*(n))+0x13c)
#define CHx_MS0_VALUE(n)				(MSCA_BASE+(0x0100*(n))+0x140)
#define CHx_MS1_POS(n)					(MSCA_BASE+(0x0100*(n))+0x144)
#define CHx_MS1_SIZE(n)					(MSCA_BASE+(0x0100*(n))+0x148)
#define CHx_MS1_VALUE(n)				(MSCA_BASE+(0x0100*(n))+0x14c)
#define CHx_MS2_POS(n)					(MSCA_BASE+(0x0100*(n))+0x150)
#define CHx_MS2_SIZE(n)					(MSCA_BASE+(0x0100*(n))+0x154)
#define CHx_MS2_VALUE(n)				(MSCA_BASE+(0x0100*(n))+0x158)
#define CHx_MS3_POS(n)					(MSCA_BASE+(0x0100*(n))+0x15c)
#define CHx_MS3_SIZE(n)					(MSCA_BASE+(0x0100*(n))+0x160)
#define CHx_MS3_VALUE(n)				(MSCA_BASE+(0x0100*(n))+0x164)
#define CHx_OUT_FMT(n)					(MSCA_BASE+(0x0100*(n))+0x168)
#define CHx_DMAOUT_Y_ADDR(n)				(MSCA_BASE+(0x0100*(n))+0x16c)
#define CHx_Y_ADDR_FIFO_STA(n)				(MSCA_BASE+(0x0100*(n))+0x170)
#define CHx_DMAOUT_Y_LAST_ADDR(n)			(MSCA_BASE+(0x0100*(n))+0x174)
#define CHx_DMAOUT_Y_LAST_STATS_NUM(n)			(MSCA_BASE+(0x0100*(n))+0x178)
#define CHx_Y_LAST_ADDR_FIFO_STA(n)			(MSCA_BASE+(0x0100*(n))+0x17c)
#define CHx_DMAOUT_Y_STRI(n)				(MSCA_BASE+(0x0100*(n))+0x180)
#define CHx_DMAOUT_UV_ADDR(n)				(MSCA_BASE+(0x0100*(n))+0x184)
#define CHx_UV_ADDR_FIFO_STA(n)				(MSCA_BASE+(0x0100*(n))+0x188)
#define CHx_DMAOUT_UV_LAST_ADDR(n)			(MSCA_BASE+(0x0100*(n))+0x18c)
#define CHx_DMAOUT_UV_LAST_STATS_NUM(n)			(MSCA_BASE+(0x0100*(n))+0x190)
#define CHx_UV_LAST_ADDR_FIFO_STA(n)			(MSCA_BASE+(0x0100*(n))+0x194)
#define CHx_DMAOUT_UV_STRI(n)				(MSCA_BASE+(0x0100*(n))+0x198)
#define CHx_DMAOUT_Y_ADDR_CLR(n)			(MSCA_BASE+(0x0100*(n))+0x19c)
#define CHx_DMAOUT_UV_ADDR_CLR(n)			(MSCA_BASE+(0x0100*(n))+0x1a0)
#define CHx_DMAOUT_Y_LAST_ADDR_CLR(n)			(MSCA_BASE+(0x0100*(n))+0x1a4)
#define CHx_DMAOUT_UV_LAST_ADDR_CLR(n)			(MSCA_BASE+(0x0100*(n))+0x1a8)
#define CHx_DMAOUT_Y_ADDR_SEL(n)			(MSCA_BASE+(0x0100*(n))+0x1ac)
#define CHx_DMAOUT_UV_ADDR_SEL(n)			(MSCA_BASE+(0x0100*(n))+0x1b0)

#define TIZIANO_ISP_IRQ_ISP_FRD                        (0)
#define TIZIANO_ISP_IRQ_STOP                           (4)
#define TIZIANO_ISP_IRQ_CTM_STATIC                     (8)
#define TIZIANO_ISP_IRQ_AE_STATIC                      (16)
#define TIZIANO_ISP_IRQ_AE_HIST                        (17)
#define TIZIANO_ISP_IRQ_AWB_STATIC                     (18)
#define TIZIANO_ISP_IRQ_AF_STATIC                      (19)
#define TIZIANO_ISP_IRQ_ADR_STATIC                     (20)
#define TIZIANO_ISP_IRQ_DEFOG_STATIC                   (21)
#define TIZIANO_ISP_IRQ_DMAOUT_FRD                     (23)
#endif
#endif
