# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_JZ4730_MIPSBOOK_400)	+= mipsbook_400.dtb
dtb-$(CONFIG_JZ4740_QI_LB60)	+= qi_lb60.dtb
dtb-$(CONFIG_JZ4770_GCW0)	+= gcw0.dtb
dtb-$(CONFIG_JZ4780_CI20)	+= ci20.dtb

dtb-$(CONFIG_INGENIC_GENERIC_BOARD)	+= mipsbook_400.dtb \
CONFIG_INGENIC_GENERIC_BOARD)
					   qi_lb60.dtb \
					   gcw0.dtb \
					   ci20.dtb