## X2000 Supported Boards
snd_halley5_v20-y := halley5_v20.o
obj-$(CONFIG_SND_ASOC_INGENIC_HALLEY5_V20) += snd_halley5_v20.o
snd_gewu-y := gewu.o
obj-$(CONFIG_SND_ASOC_INGENIC_GEWU) += snd_gewu.o
snd_kale_v10-y := kale_v10.o
obj-$(CONFIG_SND_ASOC_INGENIC_KALE_V10) += snd_kale_v10.o

## hippo Supported Boards
snd_hippo-board-y := hippo-board.o
obj-$(CONFIG_SND_ASOC_INGENIC_HIPPO_BOARD) += snd_hippo-board.o

## x1600 Supported Boards
snd_panda-y := panda.o
obj-$(CONFIG_SND_ASOC_INGENIC_PANDA) += snd_panda.o
snd_halley6-y := halley6.o
obj-$(CONFIG_SND_ASOC_INGENIC_HALLEY6) += snd_halley6.o
snd_x1600_iris-y := x1600_iris.o
obj-$(CONFIG_SND_ASOC_INGENIC_X1600_IRIS) += snd_x1600_iris.o
