ccflags-y += -I$(srctree)/drivers/mmc/host/

obj-$(CONFIG_MMC_SDHCI_INGENIC)         += sdhci-ingenic.o ingenic_sdio.o
obj-$(CONFIG_INGENIC_MMC_MMC0)  	+= ingenic_mmc.o ingenic_sdio.o
obj-$(CONFIG_INGENIC_MMC_MMC1)  	+= ingenic_mmc.o ingenic_sdio.o
