
omap_tesladriver = notify_tesla.o drv_tesla.o


obj-$(CONFIG_NOTIFY_TESLA) += notify_tesladriver.o
notify_tesladriver-objs = $(omap_tesladriver) 


ccflags-y += -Wno-strict-prototypes

#Machine dependent
ccflags-y += -DCONFIG_DISABLE_BRIDGE_PM -DDSP_TRACEBUF_DISABLED \
		-DVPOM4430_1_06

#Header files
ccflags-y += -Idrivers/dsp/syslink/inc
ccflags-y += -Iarch/arm/plat-omap/include

