omap_ducatidriver = notify_ducati.o


obj-$(CONFIG_NOTIFY_DUCATI) += notify_ducatidriver.o 
notify_ducatidriver-objs = $(omap_ducatidriver)


ccflags-y += -Wno-strict-prototypes

#Header files
ccflags-y += -Iarch/arm/plat-omap/include/
ccflags-y += -Iarch/arm/plat-omap/include/syslink

