#ifndef __INGENIC_VIDEO_NR_H__
#define __INGENIC_VIDEO_NR_H__

enum ingenic_video_nr {
	INGENIC_ROTATE_VIDEO_NR = 0,
	INGENIC_HELIX_VIDEO_NR,		/*1*/
	INGENIC_FELIX_VIDEO_NR,		/*2*/
	INGENIC_VIC0_VIDEO_NR,		/*3*/
	INGENIC_MSCA0_CH0_VIDEO_NR,	/*4*/
	INGENIC_MSCA0_CH1_VIDEO_NR,	/*5*/
	INGENIC_MSCA0_CH2_VIDEO_NR,	/*6*/
	INGENIC_VIC1_VIDEO_NR,		/*7*/
	INGENIC_MSCA1_CH0_VIDEO_NR,	/*8*/
	INGENIC_MSCA1_CH1_VIDEO_NR,	/*9*/
	INGENIC_MSCA1_CH2_VIDEO_NR,	/*10*/
	INGENIC_CIM_VIDEO_NR_0,		/*11*/
	INGENIC_UVC_VIDEO_NR,		/*12*/
	INGENIC_VIC2_VIDEO_NR,		/*13*/
	INGENIC_CIM_VIDEO_NR_1,		/*14*/
	INGENIC_DPU_COMP_VIDEO_NR,		/*15*/
};

#endif
