obj-$(CONFIG_MFD_RICOH619)      += ricoh619.o ricoh619-irq.o
obj-$(CONFIG_MFD_INGENIC_SADC_V13)      += ingenic_adc_v13.o
obj-$(CONFIG_MFD_INGENIC_SADC_AUX)      += ingenic_adc_aux.o
obj-$(CONFIG_MFD_INGENIC_TCU)   += ingenic-tcu.o
obj-$(CONFIG_MFD_INGENIC_TCU_V1)        += ingenic-tcu_v1.o
