obj-$(CONFIG_LINUX_PMEM)        += linux_pmem.o
obj-$(CONFIG_INGENIC_RSA)       += ingenic_rsa.o
obj-$(CONFIG_INGENIC_EFUSE_X2000)       += ingenic_efuse_x2000.o
obj-$(CONFIG_INGENIC_EFUSE_V2)  += ingenic_efuse_v2.o
obj-$(CONFIG_RMEM)      += rmem.o
obj-$(CONFIG_BCM_4345C5_RFKILL) += bt_power_bluesleep.o
