
#obj-$(CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5)       += cyttsp5/
obj-$(CONFIG_TOUCHSCREEN_FTS)		+= focaltech_touch/
#obj-$(CONFIG_TOUCHSCREEN_FT5X16)		+= focaltech_ft5x16_touch/
obj-$(CONFIG_TOUCHSCREEN_HYN)		+= hyn_touch/
#obj-$(CONFIG_TOUCHSCREEN_CHIPONE)		+= chipone_touch/
obj-$(CONFIG_TOUCHSCREEN_GT9XX)		+= gt9xx_touch/
obj-$(CONFIG_TOUCHSCREEN_FT6236)		+= ft6236_touch/
#obj-$(CONFIG_TOUCHSCREEN_MSM8909W)		+= msm8909w/

obj-$(CONFIG_TOUCHSCREEN_MXT336U) += mxt_336u_ts.o
