#ifndef _DT_BINDINGS_INTERRUPT_CONTROLLER_X2600_IRQ_H
#define _DT_BINDINGS_INTERRUPT_CONTROLLER_X2600_IRQ_H

#include <dt-bindings/interrupt-controller/mips-irq.h>

#define IRQ_AUDIO           (0)
#define IRQ_OTG             (1)
#define IRQ_USB             (2)
#define IRQ_PDMA            (3)
#define IRQ_PDMAD           (4)
#define IRQ_PDMAM           (5)
#define IRQ_SSI_SLAVE       (6)
#define IRQ_SFC             (7)
#define IRQ_SSI1            (8)
#define IRQ_SSI0            (9)
#define IRQ_MIPI_DSI        (10)
#define IRQ_SADC            (11)
#define IRQ_DMIC            (12)
#define IRQ_GPIO4           (13)
#define IRQ_GPIO3           (14)
#define IRQ_GPIO2           (15)
#define IRQ_GPIO1           (16)
#define IRQ_GPIO0           (17)
#define IRQ_SYS_LEP         (18)
#define IRQ_PRINTC          (19)
#define IRQ_PWM0            (20)
#define IRQ_DTRNG           (21)
#define IRQ_HASH            (22)
#define IRQ_AES             (23)
#define IRQ_WDT             (24)
#define IRQ_TCU1            (25)
#define IRQ_TCU0            (26)
#define IRQ_FELIX           (27)
#define IRQ_G2D             (28)
#define IRQ_ROTATE          (29)
#define IRQ_CIM             (30)
#define IRQ_LCD             (31)

#define IRQ_RTC             (32 + 0)
#define IRQ_SOFT            (32 + 1)
#define IRQ_CPM             (32 + 2)
#define IRQ_RESERVED0       (32 + 3)
#define IRQ_MSC1            (32 + 4)
#define IRQ_MSC0            (32 + 5)
#define IRQ_CAN1            (32 + 6)
#define IRQ_CAN0            (32 + 7)
#define IRQ_UART7           (32 + 8)
#define IRQ_UART6           (32 + 9)
#define IRQ_UART5           (32 + 10)
#define IRQ_UART4           (32 + 11)
#define IRQ_UART3           (32 + 12)
#define IRQ_UART2           (32 + 13)
#define IRQ_UART1           (32 + 14)
#define IRQ_UART0           (32 + 15)
#define IRQ_HMAN_MCU        (32 + 16)
#define IRQ_HMAN2           (32 + 17)
#define IRQ_HMAN0           (32 + 18)
#define IRQ_DDRC            (32 + 19)
#define IRQ_PCM             (32 + 20)
#define IRQ_RESERVED1       (32 + 21)
#define IRQ_EFUSE           (32 + 22)
#define IRQ_MAC             (32 + 23)
#define IRQ_I2C3            (32 + 24)
#define IRQ_I2C2            (32 + 25)
#define IRQ_I2C1            (32 + 26)
#define IRQ_I2C0            (32 + 27)
#define IRQ_MCU_PDMA        (32 + 28)
#define IRQ_MCU_PDMAD       (32 + 29)
#define IRQ_JPEGE           (32 + 30)
#define IRQ_JPEGD           (32 + 31)

#endif
