obj-y += fbdev/
obj-$(CONFIG_INGENIC_AVPU) += ingenic_avpu/
obj-$(CONFIG_INGENIC_BSCALER) += ingenic_bscaler/
obj-$(CONFIG_JZ_IPU) += ingenic_ipu/
obj-$(CONFIG_INGENIC_SOC_NNA) += ingenic-nna/
obj-$(CONFIG_TRUE_COLOR_LOGO) += logo-ingenic/
