obj-$(CONFIG_DRM_INGENIC_JZ_LCDC) += ingenic-drm.o
ingenic-drm-y = ingenic-drm-drv.o
ingenic-drm-$(CONFIG_DRM_INGENIC_IPU) += ingenic-ipu.o
obj-$(CONFIG_DRM_INGENIC_DW_HDMI) += ingenic-dw-hdmi.o
obj-$(CONFIG_DRM_INGENIC_X1000_SLCDC) += ingenic-slcd-drm.o
