# Makefile for the focaltech touchscreen drivers.
#EXTRA_CFLAGS  +=-Wno-error=date-time
# EXTRA_CFLAGS  += -Wno-date-time
obj-$(CONFIG_TOUCHSCREEN_FT6236)	+=  ft6236_touch.o
# obj-$(CONFIG_TOUCHSCREEN_GT9XX)	+=  gt9xx_update.o
# obj-$(CONFIG_TOUCHSCREEN_GT9XX)	+=  goodix_tool.o
