
obj-$(CONFIG_INGENIC_AVPU) += avpu_alloc.o	\
	  			avpu_alloc_ioctl.o \
	  			avpu_dmabuf.o	\
	  			avpu_ip.o	\
	  			avpu_main.o

#avpu_alloc.h
#avpu_alloc_ioctl.c
#avpu_alloc_ioctl.h
#avpu_dmabuf.c
#avpu_ioctl.h
#avpu_ip.c
#avpu_main.c
#avpu_no_dmabuf.c




