ingenic_fb_stage-y := ingenicfb.o\
			dpu_ctrl.o\
			hw_composer.o\
			hw_composer_fb.o\
			sysfs.o\
			jz_mipi_dsi/jz_mipi_dsi.o\
			jz_mipi_dsi/jz_mipi_dsi_lowlevel.o\
			jz_mipi_dsi/jz_mipi_dsih_hal.o
obj-$(CONFIG_FB_INGENIC_STAGE) += ingenic_fb_stage.o
obj-y += displays/

obj-y += hw_composer_v4l2.o
