obj-y += ato_nand.o gd_nand.o mxic_nand.o xtx_nand.o dosilicon_nand.o foresee_nand.o xtx_mid0b_nand.o zetta_nand.o xtx_mid2c_nand.o fm_nand.o yhy_nand.o toshiba_nand.o issi_nand.o
obj-y += nand_common.o
