#!/bin/bash
#
# build AESS firmware on PandaBoard ES with 3.15 kernel
# tested on Debian 9.13 on letux devices
#

THIS="$PWD"
BRANCH=next-bnw/ti-audio-next_3.15
VERSION=009590

#
# preparation of build host
#

echo +++ make sure we have the required build tools
yes | apt-get -y install build-essential bison flex bc libssl-dev git autogen automake libtool || exit 1

#
# getting source trees
#

function gitfetch { # $1 = repo, $2 = subdir
	echo +++ gitfetch $1 $2 +++
	if ! [ -d $2 ]
	then
		rm -rf $2.tmp
		echo git clone $1 $2.tmp
		git clone $1 $2.tmp && mv $2.tmp $2 || return
	fi
}

LINUX="$PWD/kernel"			# full source tree (for headers)
DEST="$LINUX/sound/soc/omap/aess/firmware"	# subtree where we find the firmware

echo "+++ make sure we have the (complete) kernel source tree ($BRANCH)"
( gitfetch "--depth 1 -b $BRANCH https://github.com/omap-audio/linux-audio.git" $LINUX && [ -r "$LINUX" ] ) || exit 1

echo "+++ make sure we have the audio firmware tools"
( gitfetch "--depth 1 -b peter/bnw https://github.com/omap-audio/asoc-fw.git" $DEST/asoc-fw && [ -r "$DEST/asoc-fw" ] ) || exit 1
( gitfetch "--depth 1 -b peter/bnw https://github.com/omap-audio/abefw.git" $DEST/abefw && [ -r "$DEST/abefw" ] ) || exit 1
( gitfetch "--depth 1 -b master https://github.com/omap-audio/audio-test.git" $DEST/audio-test && [ -r "$DEST/audio-test" ] ) || exit 1

#
# build firmware tools and firmware
#

echo +++ configure abefw
(
cd $DEST/abefw || exit

echo +++ autogen the Makefiles
LC_ALL=C ./autogen.sh || exit 1

echo +++ configure
# the configure option --with-hal-dir does not exist "(contrary to README)"
# ./configure --with-linux-dir=$LINUX --with-hal-dir=$PWD/hal || exit 1
./configure --with-linux-dir=$LINUX || exit 1

echo +++ make and install
make || exit 1
make install || exit 1

echo +++ generate data files
scripts/abe-tool.sh $VERSION || exit 1
) || exit

echo +++ configure asoc-fw
(
cd $DEST/asoc-fw || exit

echo +++ autogen the Makefiles
LC_ALL=C ./autogen.sh || exit

echo +++ configure
./configure --with-linux-dir=$LINUX --enable-omap4 || exit

echo +++ make and install
make || exit 1
make install || exit 1

echo "+++ finally generate firmware binary"

scripts/abegen.sh || exit 1

echo "+++ install as omap_aess-adfw.bin"
cp omap4_abe_new /lib/firmware/omap_aess-adfw.bin || exit 1

echo "+++ success ++"
ls -l /lib/firmware/omap_aess-adfw.bin
) || exit

# FIXME: build audio tools as/if needed
