#!/bin/bash

SLOT=/sys/class/retrode3/slot-md

case "$1" in

0 ) # turn off
	echo deselect >$SLOT/addr
	;;

1 ) # binary counter on address pins (is slow!)
	ADDR=0
	while true
	do
		echo addr: $ADDR
		echo $ADDR >$SLOT/addr
		ADDR=$(printf '%x' $((0x$ADDR + 2)))
	done
	;;

2 ) # one Address pin after the other
	while true
	do
		ADDR=1
		while [ $ADDR -lt 1000000 ]
		do
			echo addr: $ADDR
			echo $ADDR >$SLOT/addr
			ADDR=$(printf '%x' $((0x$ADDR * 2)))
		done
	done
	;;

3 ) # one Data pin after the other
	echo 0 >$SLOT/addr
	while true
	do
		DATA=1
		while [ $DATA -lt 10000 ]
		do
			echo data: $DATA
			echo $DATA >$SLOT/data16
			DATA=$(printf '%x' $((0x$DATA * 2)))
		done
	done
	;;

esac
