#!/bin/bash
#
# set up wlan
# connect to some network: wlan-on NETWORK -p PASSWORD
# provide some network:    wlan-on -f 2412 NETWORK -p PASSWORD
#

# to avoid wlan0: deauthenticating from c0:25:06:e4:8e:cc by local choice (Reason: 3=DEAUTH_LEAVING)
# see https://bbs.archlinux.org/viewtopic.php?id=233365
[ "$(which systemctl)" ] && systemctl disable --now NetworkManager.service wpa_supplicant.service 2>/dev/null

read -t 5 WLAN OTHER < <(iwconfig 2>&1 | fgrep 'wlan')
[ "$WLAN" ] || WLAN=wlan0

OUTPUT=/dev/null

function usage {
		echo "usage: $0 [-d dev] [ -p key ] [ -a ] [ -f freq ] | [ssid]"
		echo "  -d dev       set interface name"
		echo "  -a           ad hoc mode"
		echo "  -f freq      access point mode on frequency (e.g. 2412 + 5*i up to 2484)"
		echo "  -f 0         disable access point mode (needs a dummy SSID!)"
		echo "  -p key       Password/Key"
		echo "  ssid         SSID to connect to or use for AP"
		exit 1
}

while [ "$1" ]
do
case "$1" in
	-D )
		OUTPUT=/dev/stdout
		shift
		;;
	-d ) # set interface
		shift
		WLAN="$1"
		shift
		;;
	-a ) # create ad hoc network
		iwconfig "$WLAN" mode ad-hoc essid $(hostname) enc off channel 6 &&
		ifconfig "$WLAN" 10.1.1.1
		exit
		;;
	-f ) # switch to AP mode on frequency
		shift
		FREQ="$1"
		shift
		;;
	-p ) # set network password
		shift
		PASSWORD="$1"
		shift
		;;
	-* )
		echo unknown option "$1"
		usage;
		;;
	* ) # simple client
		if [ "$SSID" ]
		then
			echo SSID $SSID already specified
			usage
		fi
		SSID="$1"
		shift
		;;
esac
done

if [ ! "$SSID" ]
then
	echo missing SSID
	usage
fi

echo restarting wpa_supplicant

killall wpa_supplicant dhclient &>$OUTPUT
sleep 0.5
echo p2p_disabled=1 >>/etc/wpa_supplicant/wpa_supplicant.conf
wpa_supplicant -B -i "$WLAN" -c /etc/wpa_supplicant/wpa_supplicant.conf || { echo can not start wpa_supplicant; exit 1; }

echo setting up $SSID on $WLAN

wpa_cli list_networks | ( read IGNORE; read IGNORE; while read NETWORK SSID OTHER; do wpa_cli remove_network $NETWORK &>$OUTPUT; done )
wpa_cli add_network 0 &>$OUTPUT
wpa_cli set_network 0 ssid "\"$SSID\"" &>$OUTPUT || { echo invalid network name $SSID; exit 1; }

if [ "$FREQ" ]
then
	if [ "$FREQ" -ge 2412 ]
	then
		wpa_cli set p2p_disabled 1
		wpa_cli set_network 0 mode 2 &>$OUTPUT
		wpa_cli set_network 0 frequency "$FREQ" &>$OUTPUT
		wpa_cli set_network 0 auth_alg OPEN
		wpa_cli set_network 0 proto RSN
		wpa_cli set_network 0 scan_ssid 1
	else # turn off
		wpa_cli set_network 0 mode 0 &>$OUTPUT
	fi
fi

if [ "$PASSWORD" ]
then
	wpa_cli set_network 0 key_mgmt WPA-EAP WPA-PSK IEEE8021X NONE &>$OUTPUT
	wpa_cli set_network 0 psk \"$PASSWORD\" &>$OUTPUT || { echo password format mismatch; exit 1; }
else
	wpa_cli set_network 0 key_mgmt NONE &>$OUTPUT
fi
wpa_cli enable_network 0 &>$OUTPUT

[ "$OUTPUT" == /dev/stdout ] && wpa_cli save_config && cat /etc/wpa_supplicant/wpa_supplicant.conf

sleep 0.5
#wpa_cli

if [ "$FREQ" ]
then
	if [ "$FREQ" -ge 2412 ]
	then
		echo starting WLAN services on $WLAN
		ip link set "$WLAN" down
		ip addr flush dev "$WLAN"
		ip addr add 192.168.4.1/24 dev "$WLAN"
		ip link set "$WLAN" up
		# better run dnsmasq
		# or dhserver? for providing clients an address range
	else
		echo stopped WLAN services on $WLAN
	fi
else
	echo starting dhclient on $WLAN
	dhclient "$WLAN" && echo $WLAN up and running || echo $WLAN failed to connect

fi

