# stub for SGX530/540
# end

# make this compile the kernel module according to the
# description in omap5-sgx-ddk-linux/eurasia_km/INSTALL
#
# something like:
#
# 	cd drivers/gpu/pvr/omap5-sgx-ddk-linux/
#	git submodule update
#	cd eurasia_km/eurasiacon/build/linux2/omap5430_linux
#	CROSS_COMPILER=... make

obj-$(CONFIG_SGX544) += omap5-sgx-ddk-linux/eurasia_km/eurasiacon/build/linux2/omap5430_linux
