# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_DT_HALLEY5_V20)	+= halley5_v20.dtb
dtb-$(CONFIG_DT_HALLEY5_V30)	+= halley5_v30.dtb
dtb-$(CONFIG_DT_HIPPO_V10)	+= hippo_v10.dtb
dtb-$(CONFIG_DT_HIPPO_V12)	+= hippo_v12.dtb
dtb-$(CONFIG_DT_PANDA_V10)	+= panda_v10.dtb
dtb-$(CONFIG_DT_HALLEY6_V10)	+= halley6_v10.dtb
dtb-$(CONFIG_DT_LX16)		+= lx16.dtb
dtb-$(CONFIG_DT_GEWU_V10)	+= gewu_v10.dtb
dtb-$(CONFIG_DT_KALE_V10)	+= kale_v10.dtb

dtb-$(CONFIG_DT_X1000_MODULE)	+= x1000_module_base.dtb
dtb-$(CONFIG_DT_X1600_MODULE)	+= x1600_module_base.dtb
dtb-$(CONFIG_DT_X2000_MODULE)	+= x2000_module_base.dtb

obj-$(CONFIG_BUILTIN_DTB)	+= $(addsuffix .o, $(dtb-y))
