name: Kernel build tests

on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'Documentation/**'
      - 'README.md'
    branches: [ "v*" ]
  push:
    paths-ignore:
      - '.github/**'
      - 'Documentation/**'
      - 'README.md'
    branches: [ "v*" ]
  workflow_dispatch:

env:
  NUM_JOBS: 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: loshark_l1_v2.2
            arch: mipsel
            defconfig: loshark_l1_v2.2_defconfig
            image_name: uImage
          - name: loshark_l1_v2.2_lite
            arch: mipsel
            defconfig: loshark_l1_v2.2_lite_defconfig
            image_name: uImage
          - name: loshark_l1_v3
            arch: mipsel
            defconfig: loshark_l1_v3_defconfig
            image_name: uImage

    steps:
    - name: Update install
      run:
        sudo apt update

    - name: Install toolchain
      run: sudo apt install -y build-essential gcc-mipsel-linux-gnu u-boot-tools
      timeout-minutes: 5

    - name: Download binary files
      run: |
        cd /tmp
        wget -T10 https://github.com/SudoMaker/LoShark/raw/master/software/initramfs-loshark-l1-v2.2.cpio
        wget -T10 https://github.com/SudoMaker/LoShark/raw/master/software/initramfs-loshark-l1-v3.cpio
      timeout-minutes: 5

    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
        clean: true

    - name: Build kernel for ${{matrix.name}}
      run: |
        mkdir ${{github.workspace}}/build
        export ARCH=mips
        export CROSS_COMPILE=mipsel-linux-gnu-
        export IMAGE=${{matrix.image_name}}
        make O=${{github.workspace}}/build ${{matrix.defconfig}}
        make O=${{github.workspace}}/build -j ${{env.NUM_JOBS}} $IMAGE
        mkdir -p ${{github.workspace}}/install/boot/overlays
        cp ${{github.workspace}}/build/arch/${ARCH}/boot/$IMAGE ${{github.workspace}}/install/boot/${{matrix.name}}-$IMAGE.img

    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.name}}_build
        path: ${{github.workspace}}/install/boot/${{matrix.name}}-${{matrix.image_name}}.img
        retention-days: 90
