obj-$(CONFIG_ESP_HOSTED_NG)		+= esp_bt.o esp_cfg80211.o esp_cmd.o esp_debugfs.o esp_log.o esp_stats.o esp_utils.o main.o

obj-$(CONFIG_ESP_HOSTED_NG_SPI)		+= spi/esp_spi.o
obj-$(CONFIG_ESP_HOSTED_NG_SDIO)	+= sdio/esp_sdio.o sdio/esp_sdio_api.o